### ISSUE TITLE
PHP hangs on sqlsrv_query while fetching particular data

### ISSUE THREAD

**Issue by fasterforward** [Microsoft/msphpsql#623] opened 2017-12-08 09:52 UTC
# Driver version or file name
Latest stable: 4.3 from pecl.php.net

# SQL Server version
Sql Server 2008
 
# Client operating system
Ubuntu 16.04

# PHP version
PHP 7.1.12

# Microsoft ODBC Driver version
```
ubuntu@ubuntu-xenial:~$ odbcinst -j
unixODBC 2.3.1
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/ubuntu/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
ubuntu@ubuntu-xenial:~$ cat /etc/odbcinst.ini
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.1
UsageCount=1
```

# Table schema
See the reproduction script

# Problem description
PHP script hangs.

# Expected behavior and actual behavior
PHP hangs on a query containing particular data. Used the profiler and saw that the query is executed multiple times. Expected is that the data would be fetched. This is no problem with the old MSSQL extension with FreeTDS.

# Repro code

```<?php

# step 01: Connect tot database server
$server = '192.168.1.54';
$connectionInfo = [
    'Database'=>'test',
    'UID'=>'test',
    'PWD'=>'test'
];
$conn = sqlsrv_connect($server, $connectionInfo);

# step 02: Setup table
$sql = '
    CREATE TABLE [dbo].[systemtag](
        [id] [int] IDENTITY(1,1) NOT NULL,
        [name] [varchar](255) NOT NULL,
        [tag] [varchar](max) NULL,
        CONSTRAINT [PK_usertag] PRIMARY KEY CLUSTERED (
            [id] ASC
        )
    )';
$stmt = sqlsrv_query($conn, $sql);


# step 03: Insert test data
$name = 'Disclaimer e-mail';
$tag = 'De informatie van deze e-mail en de eventueel bijgevoegde bestanden is vertrouwelijk en kan juridisch beschermd zijn. Het is uitsluitend bedoeld voor degene(n) aan wie het gericht is of degene(n) die geautoriseerd zijn om het bericht te ontvangen. Indien het bericht niet voor u bestemd is, wordt u verzocht de inhoud ervan niet te lezen, en het bericht aan ons terug te sturen. In dat geval wijzen wij u er tevens op dat het kopië';

$sql = '
    INSERT INTO systemtag (
        name,
        tag
    ) VALUES (
        ?,
        ?
    )';

$parameters = [
    $name,
    $tag
];

$stmt = sqlsrv_query($conn, $sql, $parameters);


# step 04: Fetch the data
$sql = '
    SELECT
        name,
        tag
    FROM
        systemtag';

# The line below causes PHP to hang. With Sql Server Profiler I see that the query is executed multiple times.
$stmt = sqlsrv_query( $conn, $sql, [], ['Scrollable' => SQLSRV_CURSOR_CLIENT_BUFFERED]);
```
# Additional info
Before submitting the bug I tested again with the latest (preview) version of the extension: 5.1.2preview. The bug seems to be solved. ODBC driver is still version 13. Nevertheless I cannot find a bug report or something in the changelogs that points toward this problem. I could be just luck that the bug is solved. 

# Questions
Can you investigate the bug is properly solved?
Is there an ETA of the next stable version of the driver?

**Comment by david-puglielli** [comment] 2017-12-08 20:53
Hi @fasterforward thank you for reporting this. The next stable version of the driver is expected to be released early in 2018, but we will take a look at the cause of this.

**Comment by fasterforward** [comment] 2017-12-11 07:49
Hi @david-puglielli thanks for your reply. Looking forward to read about the cause!

**Comment by fasterforward** [comment] 2018-01-09 08:35
Any change @david-puglielli you had the time to look at this issue?

**Comment by yitam** [comment] 2018-01-16 00:29
Hi @fasterforward, you have probably noticed that we released the RC just before Christmas, and we are excited to tell you that we are all working hard toward pushing a stable release. Since the release of v4.3.0, we have fixed many bugs and our change log only keeps track of major issues. 

Just so you know, as explained in the [documentation](https://docs.microsoft.com/en-us/sql/connect/php/cursor-types-sqlsrv-driver), the client-side cursors should be used for small- to medium-sized result sets. You are recommended to use server-side cursors for large result sets. 

For example, in your repro scenario, since the result set contains a varchar(max) field, using the client-side cursors may not be a good idea. Alternatively, you may consider using varchar(1250) (or any column size that fits your needs) instead of varchar(max).

That being said, we are more than glad that the problem you faced before is no longer an issue with the preview version. Therefore, I hope it's alright with you that we close this issue? If not, please let us know if you still have any concerns.

**Comment by fasterforward** [comment] 2018-01-18 09:38
Hello @yitam, thanks for your reply. We used the FreeTDS en mssql extension in the past. We are trying to make a drop in replacement with the sqlsrv extension. The mssql extension always used client side cursors (so the row count could always be fetched). The application is to big to analyze all the queries at once. When the sqlsrv extension is used instead of the mssql we have the option to use server side cursors so we can adjust the application accordingly.

My only concern is that the fix is luck. Did you guys look at the root cause of it? Can you give me some guaranties that is will not happen in the future?

**Comment by yitam** [comment] 2018-01-18 16:56
Hello @fasterforward yes server side cursors are recommended if your result sets are expected to be huge. 

Please understand that we haven't had a chance to dig deeper into this issue because we have to meet the deadline to push a stable release, However, I can at least promise you that the repro scenario you have provided above will be incorporated into our test lab. In this case, if there's a regression we will know right away. What do you think?

**Comment by fasterforward** [comment] 2018-01-24 08:30
Hi @yitam! Glad to see this scenario is incorporated into the test cases. 
Are there any plans to dive deeper into this issue after the stable release is finished?

**Comment by David-Engel** [comment] 2018-01-24 23:25
Hi @fasterforward 

I can definitely sympathize with the desire to know the underlying cause for the issue. I want to know, too. To be honest, though, given that it's fixed, we have written a test to ensure the scenario is not regressed in a future release, and limited team resources, there are no plans to investigate further. If you are handy with a debugger and want to run it against the 4.3 code, please share your findings on this issue. 😃

Regards,
David

**Comment by BVisagie** [comment] 2018-01-25 08:19
Hello @David-Engel does your team have an eta for the next stable release as yet? Sorry did not see any milestone or ETA's anywhere. Thanks!

**Comment by David-Engel** [comment] 2018-01-26 20:29
@BVisagie We don't have any milestones or ETAs published. But barring any further delays, the next stable release is looking like it's going to happen early-to-mid next month.

Regards,
David

**Closed by David-Engel** 2018-01-26 20:29 UTC
Labels: Resolved, SQLSRV
