### ISSUE TITLE
money fields displayed wrong

### ISSUE THREAD

**Issue by mlhkr** [Microsoft/msphpsql#196] opened 2016-12-08 18:42 UTC
Hi All,
We're testing the 7.1 driver in our test server with full production properties.
------------------------------------
DB: SQL Server 2016 x64
OS: Windows Server 2012 R2 x64
ODBC: 13.1
PHP: 7.1 x64
-------------------------------------
The issue seems like a strange php issue but can be triggered by sql server pdo driver.
The problem is about displaying money fields.
On the PHP 5.6 version with the 5.6 pdo driver we've a code like this:
$somevariable = (float)$row['MoneyField'];
$somevariable = 2.9

On the PHP 7.1 version with the 7.1 pdo driver (nothing changed except php and driver, db, code, etc is the same)
$somevariable = (float)$row['MoneyField'];
$somevariable = 2.8999999999999999 // should be 2.9
or
$somevariable = 1.6000000000000001 // should be 1.6

Any ideas?

**Comment by yitam** [comment] 2016-12-08 21:33
@mlhkr we are unable to reproduce this issue based on your input. Would you please provide a repro script?

**Comment by mlhkr** [comment] 2016-12-08 22:02
Hi @yitam,
Now I try to reproduce and see that its connected to json_encode.
If you try to echo json_encode($data); you'll see the result like:

`
[{"MoneyField":1.5800000000000001},{"MoneyField":1.5800000000000001},{"MoneyField":1.6000000000000001},{"MoneyField":2.8900000000000001},{"MoneyField":2.8999999999999999},{"MoneyField":2.8999999999999999},{"MoneyField":2.8999999999999999},{"MoneyField":2.8999999999999999},{"MoneyField":2.8999999999999999},{"MoneyField":2.8999999999999999},{"MoneyField":2.8999999999999999}]`

Also a quick googling gave me this:
https://bugs.php.net/bug.php?id=72567&edit=1

seems like its a php 7.1 bug.

**Comment by yitam** [comment] 2016-12-08 22:28
Thanks @mlhkr for your prompt response, and indeed you're right. Once I use json_encode($data) I see the results as described.

**Comment by yitam** [comment] 2016-12-08 23:16
@mlhkr I will close this issue. Feel free to open a new one should you have other issues. Thanks.

**Closed** 2016-12-08 23:16 UTC
Labels: PDO_SQLSRV, Windows
