### ISSUE TITLE
Irregular - Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired. Only from linux

### ISSUE THREAD

**Issue by stefankaifer** [Microsoft/msphpsql#468] opened 2017-07-07 12:40 UTC
Hi

I've a big problem with PHPSQLSRV, and SQLMCD on linux, too. We have irregular (mostly every 30-40 or X  minutes) no connection to our SQL 2016 windows-server. This is the error message of sqlcmd:

> Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Timeout error [258]. .
> Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Unable to complete login process due to delay in prelogin response.
> [2017-07-07 14:00:26] Error : [1] when executing command: 'chronic /opt/mssql-tools/bin/sqlcmd -S 10.64.150.15 -d easy_prod -U myUser -P myPassword -l 2 -t 2 -Q 'SELECT @@VERSION''

I've created a BASH-script, that runs every 5 seconds SQLCMD:

> #!/bin/bash
> safeRunCommand() {
>   dt=$(date '+%Y-%m-%d %H:%M:%S');
>   typeset cmnd="$*"
>   typeset ret_code
> 
>   eval $cmnd
>   ret_code=$?
>   if [ $ret_code != 0 ]; then
>     printf "[%s] Error : [%d] when executing command: '$cmnd'" "$dt" $ret_code
>   fi
> }
> 
> LOG_FILE=/var/log/test-sqlconnection.errors.log
> command="chronic /opt/mssql-tools/bin/sqlcmd -S 10.64.150.15 -d easy_dev -U myUser -P myPassword -l 2 -t 2 -Q 'SELECT @@VERSION'"
> 
> exec 3>&1 1>>${LOG_FILE} 2>&1
> while [ "1" = "1" ]; do
>         safeRunCommand "$command"
>         sleep 3
> done

I've created a POWERSHELL-Script, that runs on a Windows2012-server and on the SQL-Server:

> FUNCTION Test-SQLConnection {
>  [CmdletBinding()]
>  Param (
>  [Parameter(Mandatory=$true)]
>  [string[]]
>  $Servers
>  ,
>          [Parameter(Mandatory=$false)] 
>         [Alias('LogPath')] 
>         [string]$Path='', 
>  [ValidateSet("String","Object")]
>  [string]
>  $OutputTo
>   
>  )
>   
> BEGIN {}
>   
> PROCESS {
>    TRY {
>     Invoke-Sqlcmd -ServerInstance 127.0.0.1 -Database easy_prod -Username myUsername -Password myPassword -ConnectionTimeout 3 -QueryTimeout 3 -Query 'SELECT @@VERSION'
>  }
>  CATCH {
>     Write-Log -Message "No connection to SQL-server" -LogPath $LogPath  
>     Write-Output "No connection to SQL-server"
>  }
>  }
> } 
>   
> }
>
> function Write-Log 
> { 
>     [CmdletBinding()] 
>     Param 
>     ( 
>         [Parameter(Mandatory=$true, 
>                    ValueFromPipelineByPropertyName=$true)] 
>         [ValidateNotNullOrEmpty()] 
>         [Alias("LogContent")] 
>         [string]$Message,
>         [Parameter(Mandatory=$false)] 
>         [Alias('LogPath')] 
>         [string]$Path='', 
>          
>         [Parameter(Mandatory=$false)] 
>         [ValidateSet("Error","Warn","Info")] 
>         [string]$Level="Info", 
>          
>         [Parameter(Mandatory=$false)] 
>         [switch]$NoClobber 
>     ) 
>     Begin 
>     { 
>         $VerbosePreference = 'Continue' 
>     } 
>     Process 
>     { 
>         if ((Test-Path $Path) -AND $NoClobber) { 
>             Write-Error "Log file $Path already exists, and you specified NoClobber. Either delete the file or specify a different name." 
>             Return 
>             } 
>         elseif (!(Test-Path $Path)) { 
>             Write-Verbose "Creating $Path." 
>             $NewLogFile = New-Item $Path -Force -ItemType File 
>             } 
>         else { 
>             } 
>         $FormattedDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss" 
>         switch ($Level) { 
>             'Error' { 
>                 Write-Error $Message 
>                 $LevelText = 'ERROR:' 
>                 } 
>             'Warn' { 
>                 Write-Warning $Message 
>                 $LevelText = 'WARNING:' 
>                 } 
>             'Info' { 
>                 Write-Verbose $Message 
>                 $LevelText = 'INFO:' 
>                 } 
>             } 
>          
>         "$FormattedDate $LevelText $Message" | Out-File -FilePath $Path -Append 
>     } 
>     End 
>     { 
>     } 
> }
> 
> $LogPath = $PSScriptRoot + "\" + $MyInvocation.MyCommand.Name -replace "ps1", "log"
> 
> while (1 -eq 1){
>     Test-SQLConnection -Servers 10.64.150.15 -LogPath $LogPath
>  
>     start-sleep -seconds 5
> }

This script runs every 5 seconds, too.

The irregular connection problems are only on the two linux-servers (same time are the problems!), not on the Windows2012-servers!

Linux-Webserver1 - 10.64.150.21, Ubuntu 16.04, msodbcsql 13.1.9.0-1, unixodbc  2.3.1-4.1, PHP7.1
Linux-Webserver2 - 10.64.150.22, Ubuntu 16.04, msodbcsql 13.1.9.0-1, unixodbc  2.3.1-4.1, PHP7.1
Windows-Webserver - 10.64.150.23, Windows 2012 R2, Powershell 5.0
SQLserver - 10.64.150.15, Windows 2012 R2, SQL 2016 Standard, Powershell 5.0

There are no activated firewalls on all of the servers. I'm connectiong over IP, not over DNS-name. All server are virtualized. We don't have any other connection problems or network problems. All the servers are in the same subnet. We have no problem by the connection from Windows-Webserver to the SQLserver, only between
Linux-Webserver1 -> SQLserver 
and
Linux-Webserver2 -> SQLserver.

Please help me to solve problem.
Best regards

Stefan

**Comment by david-puglielli** [comment] 2017-07-07 22:59
Hi @stefankaifer, this sounds like a network issue - the function that returns that particular error message reads TDS packets. Have you tried using wireshark or netcat to identify the problem?

**Comment by stefankaifer** [comment] 2017-07-12 14:49
Hi @david-puglielli, sorry, but I can't explain that (network issue). Why?

1. Same server, same subnet, only different OS:
Windows to SQL-Server: no problems in the last 5 days.
Linux (IP: 10.64.150.21) to SQL-Server (IP: 10.64.150.15): random timeouts in the last 5 days.

2. I've installed Wireshark on the SQL-machine; if I understand the wireshark log, it can't be a network issue. Why? Please see this log:

![wireshark1](https://user-images.githubusercontent.com/17417801/28123464-491b1920-6721-11e7-88d4-a39d869bd13c.png)

Please see the Line No. 29314-29325. in the first lines are everything OK, but in the last not. Same ports. Why can I see the errors (No. 29322-29325) in Wireshark, if I've a network problem? I think, that the problem is on SQL-side, or not?
But in the SQL-errorlogs I can't find an issue. Can you advice me, please?

Regards,

Stefan

**Comment by david-puglielli** [comment] 2017-07-14 21:43
You're getting RST responses, so the linux client is refusing packets from the server. My guess is a configuration issue on the client side. I would try running wireshark on the client. Also, does the problem happen if you try connecting with isql (from unixODBC) instead of sqlcmd?

**Comment by david-puglielli** [comment] 2017-07-18 00:15
@stefankaifer Please run the bash script you wrote above using `strace -tt`. `strace -tt sh <scriptname> `

When a failure occurs, inspect the timestamps and look for any backward jumps. We suspect there is a bug in the way the ODBC driver calculates clock time - it may jump backwards occasionally, possibly right when sqlcmd disconnects. Please let us know if you observe this behaviour.

**Comment by stefankaifer** [comment] 2017-07-18 04:21
@david-puglielli thanks! I'm capturing on the linux-client with tshark and I wrote a isql-script, too. Since yesterday there was no connection issue with isql, but with sqlcmd again!

My isql-command:
`chronic /usr/bin/isql -v SECTION_FROM_ODBC.INI USERNAME PASSWORD -b < isql.sql`

There could be a timestamp issue, your're right. Please see my log of the sqlcmd-script:

`[2017-07-16 21:34:50] Error : [1] when executing command: 'chronic /opt/mssql-tools/bin/sqlcmd -S db-easy-pilot.HE.DIR -d easy_pilot -U easy -P u5LWhfmEtF8B2TYN -l 2 -t 2 -Q 'SELECT @@VERSION''[2017-07-16 21:34:50] Error : [1] when executing command: 'chronic /opt/mssql-tools/bin/sqlcmd -S db-easy-prod.HE.DIR -d easy_prod -U easy -P u5LWhfmEtF8B2TYN -l 2 -t 2 -Q 'SELECT @@VERSION''Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x102.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
[2017-07-17 21:33:57] Error : [1] when executing command: 'chronic /opt/mssql-tools/bin/sqlcmd -S db-easy-pilot.HE.DIR -d easy_pilot -U easy -P u5LWhfmEtF8B2TYN -l 2 -t 2 -Q 'SELECT @@VERSION''Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x102.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
[2017-07-17 21:33:57] Error : [1] when executing command: 'chronic /opt/mssql-tools/bin/sqlcmd -S db-easy-prod.HE.DIR -d easy_prod -U easy -P u5LWhfmEtF8B2TYN -l 2 -t 2 -Q 'SELECT @@VERSION''Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Query timeout expired.
[2017-07-17 21:33:55] Error : [1] when executing command: 'chronic /opt/mssql-tools/bin/sqlcmd -S db-easy-prod.HE.DIR -d easy_prod -U easy -P u5LWhfmEtF8B2TYN -l 2 -t 2 -Q 'SELECT @@VERSION''Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x102.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
[2017-07-17 21:34:02] Error : [1] when executing command: 'chronic /opt/mssql-tools/bin/sqlcmd -S db-easy-pilot.HE.DIR -d easy_pilot -U easy -P u5LWhfmEtF8B2TYN -l 2 -t 2 -Q 'SELECT @@VERSION''Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x102.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
[2017-07-17 21:34:02] Error : [1] when executing command: 'chronic /opt/mssql-tools/bin/sqlcmd -S db-easy-prod.HE.DIR -d easy_prod -U easy -P u5LWhfmEtF8B2TYN -l 2 -t 2 -Q 'SELECT @@VERSION''Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x102.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
`

First problem at 21:34:50, but the second at 21:33:57, the timestamp should be a later one, it couldn't be earlier!
Maybee my provider (it is a cloud vmware-server) activated the option "Time synchronisation" in the vmware-options. I'll check it.

Here is a screenshot of the tshark-capture on the linux-client:

![image](https://user-images.githubusercontent.com/17417801/28300656-4afa05ee-6b81-11e7-98ea-64886a5e4357.png)

 I'll trying your posted strace-command.

**Comment by v-chojas** [comment] 2017-07-18 15:36
That will strace the /bin/bash, which won't log anything about sqlcmd. Instead, you should run strace on sqlcmd inside the script, and have the script exit the loop when sqlcmd fails. That way you will obtain the log of a failure only, and not spend huge amounts of disk space logging successful runs.

**Comment by stefankaifer** [comment] 2017-07-21 06:39
Thanks, v-chojas. I've modified my script, but since two days I haven't any issues (==> no strace-log). It's very strange!
I've changed only one thing: because of the above "isql"-test, I've created the file /etc/odbc.ini (it wasn't there by default installation). But I don't belive, that it is the solution. I'm investigating further...

**Comment by david-puglielli** [comment] 2017-07-22 23:30
Adding an odbc.ini file is not relevant to the problem I think. Please do keep us apprised of any further developments though!

**Comment by stefankaifer** [comment] 2017-07-26 06:18
thanks, guys. I had the problem 2 or 3 times in the last days again. I've attached the strace-output.

[strace-2017-07-24-21-33-59.txt](https://github.com/Microsoft/msphpsql/files/1175605/strace-2017-07-24-21-33-59.txt)
[strace-2017-07-24-21-34-19.txt](https://github.com/Microsoft/msphpsql/files/1175606/strace-2017-07-24-21-34-19.txt)
[strace-2017-07-25-19-58-19.txt](https://github.com/Microsoft/msphpsql/files/1175607/strace-2017-07-25-19-58-19.txt)

**Comment by david-puglielli** [comment] 2017-07-31 23:29
@stefankaifer I believe you are still using strace on bash, you must run it on sqlcmd inside the script. There doesn't seem to be anything unusual in the logs you have provided.

**Comment by Hadis-Fard** [comment] 2017-08-23 21:09
@stefankaifer Have you had a chance to try strace on command as @david-puglielli suggested?

**Comment by yitam** [comment] 2017-11-16 19:55
@stefankaifer do you have any update on this?

**Comment by stefankaifer** [comment] 2017-11-20 10:59
Hi guys, sorry for the late answer, but I had a lot of todos in the last weeks.
The problem is existing sometimes. My problem is, that I don't know how to run the strace command crrectly. I've read @david-puglielli's answer

> @stefankaifer I believe you are still using strace on bash, you must run it on sqlcmd inside the script. There doesn't seem to be anything unusual in the logs you have provided.

but I don't know, ho to do it right. Can seomebody modify my script, please?

`#!/bin/bash
safeRunCommand() {
  dt=$(date '+%Y-%m-%d %H:%M:%S');
  dtlog=$(date '+%Y-%m-%d-%H-%M-%S');
  LOG_FILE_STRACE="/var/log/strace-$dtlog.log"  
  typeset cmnd="$*"
  typeset ret_code

  #echo cmnd=$cmnd
  eval $cmnd
  ret_code=$?
  if [ $ret_code != 0 ]; then
	strace -tt -f -o $LOG_FILE_STRACE /opt/mssql-tools/bin/sqlcmd -S 192.168.225.147 -d easy_dev -U myUser -P myPassword -l 2 -t 2 -Q 'SELECT @@VERSION'
    printf "[%s] Error : [%d] when executing command: '$cmnd'" "$dt" $ret_code
# | tee /dev/fd/3
    #exit $ret_code
  fi
}

LOG_FILE=/var/log/test-sqlconnection.errors.log
command="chronic /opt/mssql-tools/bin/sqlcmd -S 192.168.225.147 -d easy_dev -U myUser -P myPassword  -l 2 -t 2 -Q 'SELECT @@VERSION'"

exec 3>&1 1>>${LOG_FILE} 2>&1
while [ "1" = "1" ]; do
	safeRunCommand "$command"
	sleep 3
done`

**Comment by david-puglielli** [comment] 2017-11-20 21:11
You are running strace correctly - the problem is that the error happens only occasionally, so if you run strace only when an error occurs, the error will probably not occur again if you run the same command again under strace. 

What version of the ODBC driver are you using? I would suggest upgrading to version 17, available [here](https://github.com/Microsoft/msphpsql/tree/dev/ODBC%2017%20binaries%20preview). The bug that causes time to jump backwards has been fixed in version 17, so upgrading may solve your issue.

**Comment by stefankaifer** [comment] 2017-11-21 08:34
@david-puglielli Thanks. I had version 13, now I've installed version 17 on my development system. I'm observing...

**Comment by stefankaifer** [comment] 2017-12-11 16:29
Hi guys,

I think, that with the current odbc-version (17) the problem is gone! I hadn't drops in the past 2 weeks.
Thank you very much for the support!
Regards

Stefan

**Comment by david-puglielli** [comment] 2017-12-11 18:59
Glad we could help! You may also be interested to know, we will upload an updated ODBC driver 17 later this month as well.

Closing the issue.

**Closed by david-puglielli** 2017-12-11 18:59 UTC

**Comment by jeff1985** [comment] 2017-12-18 08:14
@stefankaifer 
I'm experiencing a similar issue, which might be connected to this case. Could you clarify: were you using persistent database connections (connection pooling) in your setup?

**Comment by stefankaifer** [comment] 2018-01-11 12:20
@jeff1985 I'm using **no** persistant connections.

**Comment by pmartelletti** [comment] 2018-02-05 18:16
@david-puglielli I've tried upgrading to version 17 of the driver, but got:

>   SQLSTATE[IMSSP]: This extension requires the Microsoft ODBC Driver 13 for SQL Server to communicate with SQL Server

Does that means that v17 is not supported with sqlsrv driver for PHP? or that is not finding the driver at all?

Problem I'm getting is that after 2/3 minutes of the driver running correctly, I get timeout login for all of the connections (even if I try to reconnect again).

Tried enabling pooling and increasing CPTimeout, but nothing helped. 😟

**Comment by david-puglielli** [comment] 2018-02-05 20:56
@pmartelletti Please try adding the Driver keyword to your connection string and specifying version 17, like this:
```
Driver={ODBC Driver 17 for SQL Server};
```
This will override the default ODBC driver version.

**Comment by pmartelletti** [comment] 2018-02-06 09:47
@david-puglielli hmm.. I'm using:

```
'driver' => 'sqlsrv',
```

how should I specify the version there? `sqlsrv17` won't work.

**Comment by pmartelletti** [comment] 2018-02-06 16:08
@david-puglielli  sorry, just realised you were referring to the `.odbcinst.ini` file.

Changed that to look something like this, in all the locations that I could find:

```
/etc/odbcinst.ini
/home/forge/.odbcinst.ini
/opt/microsoft/msodbcsql/etc/odbcinst.ini
```
to look something like this:
```
[ODBC]
Pooling=No

[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
#Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.2
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-17.0.so.0.5
UsageCount=1
```

but still getting from PHP the following:

> Can't open lib 'ODBC Driver 13 for SQL Server' : file not found

So seems like it's still trying to use the v13 of the driver.

Any ideas?

**Comment by pmartelletti** [comment] 2018-02-06 16:33
@david-puglielli is it possible that the PHP driver only works with the ODCB Driver 13, as per this list? Or that's just listing stable releases?

https://docs.microsoft.com/en-us/sql/connect/php/system-requirements-for-the-php-sql-driver

**Comment by david-puglielli** [comment] 2018-02-06 18:51
That page just lists stable releases. The latest preview (5.2.0-RC) supports ODBC 17. To use ODBC 17, instead of `'driver=>'sqlsrv'`, use 
```
'driver'=>"ODBC Driver 17 for SQL Server"
```
in your PHP script. To make sure you are using a supported version of the drivers, run
```
php --ri sqlsrv
php --ri pdo_sqlsrv
```
from the command line and verify that `ExtensionVer` is at least 5.2.0.
