### ISSUE TITLE
RESTORE DATABASE broken

### ISSUE THREAD

**Issue by pakomp** [Microsoft/msphpsql#932] opened 2019-02-18 09:10 UTC
## PHP Driver version or file name
ExtensionVer => 5.3.0
## SQL Server version
SQL Server 14.0.2002.14
## Client operating system
Debian 9
## PHP version
PHP 7.2.14
## Microsoft ODBC Driver version
ODBC Driver for Microsoft SQL Server 17.2.0.1
## Problem description
RESTORE DATABASE sqlsrv_query returns false
and "Processed XXX pages for database..." error

## Expected behavior and actual behavior
I expected the database to be restored into a functional state, which has worked in PHP 5.6 using the mssql driver.

What actually happens is sqlsrv_query returns false and sqlsrv_errors(SQLSRV_ERR_ERRORS) gives "Processed XXX pages for database..." and the database is left in Restoring... state
I have set sqlsrv_configure("WarningsReturnAsErrors",0) so I dont see why I get this as an error.

Seems to be a known issue from 2010
https://blogs.msdn.microsoft.com/brian_swan/2010/04/13/working-down-the-stack-enabling-odbc-tracing-with-the-sql-server-driver-for-php/
https://blogs.msdn.microsoft.com/brian_swan/2010/07/01/restoring-a-sql-server-database-from-php/
which then could be fixed by running a 
USE TestDB 
query after the RESTORE DATABASE query.

But that doesnt work for me and sqlsrv_query didnt return false in his blog post either so guess the issue has gotten worse since 2010.

## Repro code or steps to reproduce
Call sqlsrv_query with $sql RESTORE DATABASE TestDB FROM DISK='C:\Backups\testdb.bak'

**Comment by david-puglielli** [comment] 2019-02-19 21:45
@pakomp I can reproduce the behaviour you see, except that USE TestDB works if I call it immediately after attempting the RESTORE query (if I try reconnecting or call it from a different script, then it fails).

Have you tried to restore the database using sqlcmd?

**Comment by pakomp** [comment] 2019-02-20 11:10
Running the code from the blog the output I get is

`RESTORE DATABASE TestDB FROM DISK = '//10.164.XXX.YYY/BAK/sql.bak'  WITH RECOVERY
Array ( [0] => Array ( [0] => 01000 [SQLSTATE] =>  01000 [1] => 4035 [code] => 4035 [2] => [Microsoft][ODBC Driver 17 for  SQL Server][SQL Server]Processed 1046528 pages for database 'TestDB', file  'Data' on file 1. [message] => [Microsoft][ODBC Driver 17 for SQL  Server][SQL Server]Processed 1046528 pages for database 'TestDB', file  'Data' on file 1. ) ) 
USE TestDB
Array ( [0] => Array ( [0] => 42000 [SQLSTATE] => 42000 [1] => 927  [code] => 927 [2] => [Microsoft][ODBC Driver 17 for SQL Server][SQL  Server]Database 'TestDB' cannot be opened. It is in the middle of a restore.  [message] => [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Database  'TestDB' cannot be opened. It is in the middle of a restore. ) )
`

Using sqlcmd works, but I cant pass the correct login password to that since it doesnt have anyway to handle characters that needs escaping, so I cant use that as a workaround.

**Comment by david-puglielli** [comment] 2019-02-20 20:31
Thank you @pakomp. We will investigate this issue and get back to you.

**Comment by yitam** [comment] 2019-02-28 18:42
@pakomp please elaborate what you meant by not being to escape characters using sqlcmd. FYI, you might find [this question on stackoverflow ](https://stackoverflow.com/questions/17041145/escaping-special-symbols-in-sqlcmd)useful

**Comment by pakomp** [comment] 2019-03-04 07:03
The character I seem to have problem with is using " in the password, without it I seem to be able to supply the password as both -P <password> or -P '<password>'. 

But when I add the " to the password I just get
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login failed for user
however I try.

Feels like that stackoverflow question is about how windows handles escaping, which doesnt help me much when using bash on linux.

**Comment by yitam** [comment] 2019-03-04 16:15
@pakomp, I forgot to mention last time, as @david-puglielli pointed out earlier, 
> USE TestDB works if I call it immediately after attempting the RESTORE query 

That is, the workaround `USE TestDB` still works if it is called *immediately* after the RESTORE query (do not disconnect in between).

Meanwhile, we will continue investigating the root cause.

**Comment by yitam** [comment] 2019-03-05 01:44
@pakomp to use sqlcmd with a password with special characters, you can try running sqlcmd like this:
`sqlcmd -S <yourserver> -U <userid>`

This will prompt you for your password, which you should enter directly. There is no need to escape any character.

Concerning the RESTORE DATABASE query (the same applies to BACKUP DATABASE as well), the operation generates lots of informational messages like `0% complete ... 10% complete ... 20% complete ...` etc. Therefore, the client should process messages like "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Processed <number> pages for database 'test_database', file 'test_database_log' on file 1."

The larger the database, the more of such messages you will have to process. Otherwise, the server will stop in the middle of the task. When using the ODBC driver, we should keep invoking SQLMoreResults() and reading diag recs until no more are found until the operation completes successfully.

When using PHP, we could do something like this:

```
    //Restore DB.
    $sql = "RESTORE DATABASE $database FROM DISK = '$backup_file' WITH RECOVERY";    
    echo "Query: $sql" . PHP_EOL;
    $stmt = sqlsrv_query($conn, $sql);
    if ($stmt === false) {
        die(print_r(sqlsrv_errors()));
    } else {
        echo "Database being restored from $backup_file..." . PHP_EOL;
        print_r(sqlsrv_errors());
    }
    
    while ($next_result = sqlsrv_next_result($stmt)) {
        print_r(sqlsrv_errors());
    }
```

Therefore, when it's successfully finished, you should expect to receive a message like this one:

` [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]RESTORE DATABASE successfully processed 299 pages in 0.089 seconds (26.246 MB/sec).`

Here are some references for your interest:

https://stackoverflow.com/questions/278359/sql-server-backup-database-over-odbc
http://otl.sourceforge.net/otl4_ex688.htm

**Comment by pakomp** [comment] 2019-03-05 09:46
I was running 
sqlsrv_configure("WarningsReturnAsErrors",0);
to late in my code, after moving it up before the sqlsrv_connect call then
$stmt = sqlsrv_query($conn, $sql);
stopped returning false, and I could call sqlsrv_next_result to get the db to restore.

Why are all messages treated like warnings?

**Comment by yitam** [comment] 2019-03-05 17:45
hi @pakomp 

By default, [`WarningsReturnAsErrors` is true](https://docs.microsoft.com/sql/connect/php/how-to-configure-error-and-warning-handling-using-the-sqlsrv-driver?view=sql-server-2017), and the user has to deliberately turn it off by setting it to false.

The RESTORE DATABASE operation actually returns `SQL_SUCCESS_WITH_INFO`, and by calling the [SQLGetDiagRec Function](https://docs.microsoft.com/sql/odbc/reference/syntax/sqlgetdiagrec-function?view=sql-server-2017) it retrieves any error, warning, and/or status information. 

In this case, the messages are returned as warnings. If you are concerned about setting `WarningsReturnAsErrors` to false, you can also turn on [logging](https://docs.microsoft.com/sql/connect/php/logging-activity?view=sql-server-2017), like this:

```
sqlsrv_configure("WarningsReturnAsErrors", 0);
sqlsrv_configure("LogSeverity", SQLSRV_LOG_SEVERITY_ALL);
sqlsrv_configure("LogSubsystems", SQLSRV_LOG_SYSTEM_CONN | SQLSRV_LOG_SYSTEM_STMT);
```

When you give this a try, you will see that the messages returned are basically informational messages with [SQLSTATE = 01000](https://www.easysoft.com/developer/interfaces/odbc/sqlstate_status_return_codes.html#01000)

**Comment by yitam** [comment] 2019-03-06 17:12
@pakomp I believe this issue is resolved. I'm closing this issue, but please feel free to reopen.

**Closed by yitam** 2019-03-06 17:12 UTC
