### ISSUE TITLE
Can't connect to SQL Server from Ubuntu 17.10

### ISSUE THREAD

**Issue by danjboyd** [Microsoft/msphpsql#771] opened 2018-05-10 21:50 UTC
I am attempting to connect to two different SQL servers in my company.

My setup:
Ubuntu 17.10
SQL Server ODBC driver 17.1.0.1-1
SQL Server Version 10.0.5538.0

/etc/odbcinst.ini
[ODBC Driver 17 for SQL Server]
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.1.so.0.1
UsageCount=1
Trace=yes

/etc/odbc.ini
[AccountingLedger]
Driver= ODBC Driver 17 for SQL Server
Server=MY.FQDN.SERVER.NAME
ServerSPN = MSSQLSvc/:
Database=Accounting_Ledger
Trusted_Connection=yes

I successfully authenticated with my domain using kinit and klist shows a valid ticket cache

> sqlcmd -E -S AccountingLedger
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x102.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..

In addition, I have a second server that I'm trying to authenticate to with SQL credentials:

from /etc/odbc.ini
[Kingdom]
Driver = ODBC Driver 17 for SQL Server
Server=WHR-IHS\KINGDOMSQL
Database=WHR_Giddings_95

> sqlcmd -S Kingdom -Uusername -Ppassword
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x102.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..

I am able to connect to both of these servers via System.Data.SqlClient in Mono from this same machine as well as with DBeaver/Eclipse...

**Comment by danjboyd** [comment] 2018-05-10 21:51
Oh -- and the second SQL server is a different version -- 12.0.5207.0

**Comment by david-puglielli** [comment] 2018-05-11 17:54
@danjboyd It's not clear what the problem might be, but one thing stands out - it looks like you are using a named instance for your second server. When using a named instance, you must specify the port in the connection string. See #442 and [this page](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns?view=sql-server-2017). 

For your first server, I suspect the problem is with the ServerSPN line. You need a fully qualified domain name and a port number. See [this page](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-linux-2017). Note however ServerSPN is [not supported](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication?view=sql-server-2017) with integrated authentication.

**Comment by david-puglielli** [comment] 2018-06-22 03:54
@danjboyd Have you solved the problem? Please let us know - if there is no further activity on this issue, we will close it in a few days.

**Comment by david-puglielli** [comment] 2018-06-27 23:29
Closing issue. Feel free to reopen if needed.

**Closed by david-puglielli** 2018-06-27 23:29 UTC
