### ISSUE TITLE
Negative field length calculated in buffered result set in...

### ISSUE THREAD

**Issue by iamthefox** [Microsoft/msphpsql#564] opened 2017-10-04 01:51 UTC
Ran into a weird issue possibly related to (n)varchar max fields. 

Running faulty query in isolation does not allow me to replicate the issue so I think it has something to do with the buffer size overflow. 

I've bumped buffer size to a 512mb and it did not help. 

I found a reference here https://github.com/Microsoft/msphpsql/blob/master/source/shared/core_results.cpp#L1335 but can't tell what could be causing it. 

If I can provide more information please let me know. 

My setup:
Ubuntu 16.04
pdo_sqlsrv/sqlsrv: 4.3.0 (stable)
unixodbc: 2.3.1
msodbcsql: 13.1.9.1

Connection pooling - ON
Buffered queries - ON example below. 
```
$options = [
                PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL,
                PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE => PDO::SQLSRV_CURSOR_BUFFERED
            ];

$statement = $result->prepare($query, $options);
$statement->execute();
```

**Comment by david-puglielli** [comment] 2017-10-04 03:47
Hi @iamthefox, does the error occur only with varchar(max) or nvarchar(max), or with other (n)varchar fields? If providing a repro script is not feasible, any more information you can provide about the query or script that causes the error would help.

Also, please try upgrading to the latest release of the sqlsrv drivers. You can download them from [here](https://github.com/Microsoft/msphpsql/releases/tag/v5.1.0-preview) or with pecl (instructions on the [Readme](https://github.com/Microsoft/msphpsql/blob/dev/README.md)).

**Comment by iamthefox** [comment] 2017-10-04 10:55
Hi @david-puglielli,

Thanks for a quick response. 

I spent some time and managed to consistently replicate this issue in isolated environment.

Here is the script that dies with the error that I described earlier. 

```php
<?php

function microtime_float()
{
    list($usec, $sec) = explode(" ", microtime());
    return ((float)$usec + (float)$sec);
}

$start_time = microtime_float();

for ($i = 0; $i <= 9; $i++) {
    $server = '...';
    $database = '...';
    $userName = '...';
    $password = '...';
    $dsn = "sqlsrv:server=$server; Database=$database; App=test_php7_script";
    try {
        $pdo = new PDO($dsn, $userName, $password);
        $pdo->setAttribute(PDO::ATTR_STRINGIFY_FETCHES, false);
        $pdo->setAttribute(PDO::SQLSRV_ATTR_FETCHES_NUMERIC_TYPE, true);
        $query = "
            SET NOCOUNT ON;
            declare @TEMP table ([key] varchar(255), [value] varchar(max));
            insert into @TEMP VALUES('key1', 'yes');
            insert into @TEMP VALUES('key2', 'no');
            insert into @TEMP VALUES('key3', 'no');
            insert into @TEMP VALUES('key4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli');
            SELECT [key], [value] FROM @TEMP
        ";
        $options = [
            PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL,
            PDO::SQLSRV_ATTR_CURSOR_SCROLL_TYPE => PDO::SQLSRV_CURSOR_BUFFERED
        ];
        $stm = $pdo->prepare($query, $options);
        $stm->execute();
        echo 'LEVEL ' . $i . ' ' . PHP_EOL;
        while ($row = $stm->fetch(PDO::FETCH_ASSOC)) {
            echo $row['value'] . PHP_EOL;
        }
    } catch (PDOException $e) {
        echo $e->getMessage();
    }
}
echo "\nEND TIME ===== ";
$end_time = microtime_float();
$time = round($end_time - $start_time, 4);
echo $time;

die;
```

PS

I tried the latest version of this driver and unfortunately it did not fix the issue.

**Comment by david-puglielli** [comment] 2017-10-05 00:02
Unfortunately I cannot reproduce the issue with this script. What is the exact output that you get from the script? Also, what version of SQL Server are you running?

**Comment by iamthefox** [comment] 2017-10-05 01:02
So I tried 4 variations here:

1. Connection pooling on (in odbcinst.ini) + Buffered queries
I get following result
```
LEVEL 0
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 1
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 2
yes
no
no
PHP Fatal error:  Negative field length calculated in buffered result set in /var/www/bookmaker/do-not-checkin/dbtest.php on line 40
```

2. Connection pooling on - Unbuffered queries
```
LEVEL 0
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 1
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 2
yes
no
no

LEVEL 3
yes
no
no

LEVEL 4
yes
no
no

LEVEL 5
yes
no
no

LEVEL 6
yes
no
no

LEVEL 7
yes
no
no

LEVEL 8
yes
no
no

LEVEL 9
yes
no
no
```

As you can see it does not throw an errors for unbuffered queries BUT it returns empty results for the long string. 

3. Connection pooling on. Buffered queries + forcing system encoding (could be irrelevant but I decided to include this test as well) 

```
LEVEL 0
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 1
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 2
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermen���U�@�X�U���������h��U�����
LEVEL 3
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermen���U���H��U�@
�U�nokey2
LEVEL 4
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermen���U�@�X�U�����������U�
LEVEL 5
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermen���U���H��U�@
�U�nokey2
LEVEL 6
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermen���U�@�X�U���������������������
LEVEL 7
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermen���U���H��U�@
�U�nokey2
LEVEL 8
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermen���U�@�X�U�key1
LEVEL 9
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermen���U���H��U�@
�U�nokey2
```

This one returns all the data, does not throw any errors but data looks malformed. 

4. Connection pooling off, buffered queries/unbuffered queries
 
```
LEVEL 0
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 1
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 2
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 3
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 4
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 5
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 6
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 7
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 8
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
LEVEL 9
yes
no
no
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum rutrum sodales. Nullam mattis fermentum libero, non volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing eli
```

Thats exactly what we expect to see and it only works with the pooling off :(

As for the sql server we use SQL Server 2014 that is running in 2008 compatibility mode. It's running on a separate Windows Server 2008 R2 instance. Note: php(7) is running on ubuntu 16.04

**Comment by iamthefox** [comment] 2017-10-05 05:08
Hey @david-puglielli 

I found the way to replicate it using official/latest docker images. 

Step 1.
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d microsoft/mssql-server-linux:2017-GA

Step 2. 
I built another docker instance using this repo https://github.com/Microsoft/mssql-docker/tree/master/oss-drivers/msphpsql

Step 3.
SSH into 2nd image and modify /etc/odbcinst.ini to enable pooling

In my case my config is as simple as this 
```
[ODBC]
Pooling=Yes

[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.1
UsageCount=1
CPTimeout=120
```

Step 4. 
```
cd /sample
vim sample.php
# put the replication script here
# note: you will need to point db to the image we created in step 1
```

Step 5.
```
php sample.php
```

For me it dies on 3d iteration with connection pooling on and works correctly with pooling off.

**Comment by david-puglielli** [comment] 2017-10-05 18:38
Thanks @iamthefox I can now reproduce the issue, it seems turning connection pooling on was the key. We will investigate and keep you updated.

**Comment by iamthefox** [comment] 2017-10-06 00:05
no worries @david-puglielli 

I've tried one more case and when I do unbuffered queries with `        $pdo->setAttribute(PDO::SQLSRV_ATTR_ENCODING, PDO::SQLSRV_ENCODING_SYSTEM);
` set it works as expected even with pooling on.

**Comment by yitam** [comment] 2017-10-12 19:08
@iamthefox thanks for your patience. Regrettably the problem boils down to [unixodbc restrictions with connection pooling](http://www.unixodbc.org/doc/conn_pool.html). When connection pooling is enabled in a non-Windows environment, we have to connect using SQLDriverConnect() instead of its wide version. 

Just as you have brilliantly pointed out above, once you have set `$pdo->setAttribute(PDO::SQLSRV_ATTR_ENCODING, PDO::SQLSRV_ENCODING_SYSTEM);` the buffer miscalculation is gone. The reason is that the contents in the client buffers are stored based on the size of a regular character rather than a wide character (the default case). 

Unfortunately, this problem remains even in unixodbc 2.3.4 (it's 2.3.1 in Ubuntu 16.04). For your interest you can see these links [pyodbc 283](https://github.com/mkleehammer/pyodbc/issues/283) and [unixODBC 2](https://github.com/lurcher/unixODBC/pull/2).

Hope this helps.

**Comment by Hadis-Fard** [comment] 2017-10-18 22:19
Closing this issue as it is unixODBC issue

**Closed by Hadis-Fard** 2017-10-18 22:19 UTC
Labels: linux, unixODBC
