### ISSUE TITLE
An exception is thrown during shutdown if the connection is broken during script execution (pdo_sqlsrv)

### ISSUE THREAD

**Issue by Agares** [microsoft/msphpsql#1089] opened 2020-02-05 15:45 UTC
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 ## PHP Driver version or file name
 5.8.0 (from https://pecl.php.net/package/pdo_sqlsrv/5.8.0/windows)
 ## SQL Server version
 Microsoft SQL Server 2017 (RTM-CU8) (KB4338363) - 14.0.3029.16 (X64)   Jun 13 2018 13:35:56   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 16.04.4 LTS)
 ## Client operating system
 Windows 10 Enterprise
 ## PHP version
 PHP 7.4.2 (cli) (built: Jan 21 2020 17:52:43) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.2, Copyright (c) 2002-2020, by Derick Rethans
 ## Microsoft ODBC Driver version
 
 ## Table schema
```
CREATE DATABASE test
GO
```
Tables do not matter
## Problem description
If the session is killed, an exception is thrown both during query execution using that connection AND during php shutdown
## Expected behavior and actual behavior
An exception is thrown only during query execution.
## Repro code or steps to reproduce
```php
<?php
$pdo = new \PDO('sqlsrv:Server=localhost,1434;Database=test;MultipleActiveResultSets=false', 'sa', '...');
$pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
$stmt = $pdo->prepare('SELECT @@SPID');
$stmt->execute();
$spid = $stmt->fetchColumn();

// if this transaction is removed, the issue disappears
$pdo->beginTransaction();

$pdo2 = new \PDO('sqlsrv:Server=localhost,1434;Database=test', 'sa', '...');
$r = $pdo2->prepare('KILL ' . $spid)->execute();
var_dump($r);

try {
	$r = $pdo->prepare('SELECT 1')->execute();
	var_dump($r);
} catch(\PDOException $e) {
}

echo 'After try/catch'.PHP_EOL;

exit(2);
```

**Comment by david-puglielli** [comment] 2020-02-05 20:09
@Agares thank you for this report. We will investigate and get back to you.

**Comment by david-puglielli** [comment] 2020-02-13 01:43
After some investigation, the uncaught exception happens when there is an unfreed statement that PHP must clean up on script termination. This causes an exception because the connection was broken, and the exception can't be caught because it occurs on termination. Note that if there is an open transaction, the connection will not re-establish itself, so an exception would be expected. But this exception would occur because PHP is trying to free a broken connection, and this exception is catchable. The exception here is instead because the very first statement, `$stmt` is never freed, and an exception is thrown trying to free the statement at termination. It is not possible to catch this exception, even if trying to free the connection with (say) `unset($pdo);`.

Therefore as a workaround, free the statement before the script terminates with `unset($stmt);`. This error also happens on sqlsrv, but it does not throw an exception - it rather just gets copied to the `sqlsrv_errors()` array. We will look more closely at how to alter pdo_sqlsrv's behaviour in the near future.

**Comment by david-puglielli** [comment] 2020-02-15 00:17
After further investigation, we believe this is by design. Explanation: This behaviour is almost identical to pdo_odbc, except that pdo_odbc does not throw the uncaught exception at the end. However, like pdo_sqlsrv, it only attempts to free the statement at script termination, even after calling `unset($pdo)` (which apparently does nothing when the connection is broken and a statement is not explicitly unset). It then calls SQLEndTran, which returns -1 and the error `Communication link failure`. It does not throw an exception unless `dbh->methods` is undefined (see line 106 of pdo_odbc/odbc_driver.c), though why this condition is relevant is a mystery - it probably *should* throw on this particular error. 

It appears that PDO does not free the connection when unset is called - instead it waits until the script terminates to start freeing resources. The exception is because, with an active transaction on a broken connection, SQLEndTran returns an error, which is thrown by zend_throw_exception. This exception would be catchable if $stmt is unset explicitly, but as PDO is waiting until termination to free $stmt, the error is not catchable, resulting in a fatal exception.

So the error is expected because there is an active transaction on a broken connection. Connection resiliency does not apply when a transaction is active - see [this page](https://docs.microsoft.com/sql/connect/php/connection-resiliency) and [this technical article](http://download.microsoft.com/download/D/2/0/D20E1C5F-72EA-4505-9F26-FEF9550EFD44/Idle%20Connection%20Resiliency.docx). PHP's behaviour when freeing resources causes the uncatchable exception, but this can be fixed by explicitly freeing any active statement with `unset($stmt)`. So we will mark this behaviour as being by design.

We will leave this issue open for a little while longer in case there are any questions.

**Comment by david-puglielli** [comment] 2020-02-21 21:56
This problem fundamentally appears to be because PDO does not have a dedicated method for closing connections. The PDO documentation on [connection management](https://www.php.net/manual/en/pdo.connections.php) mentions the need to free the statement first, but multiple users on that page and [this bug report](https://bugs.php.net/bug.php?id=62065) also point out that a dedicated close() method would be better than setting a connection to null or unsetting it.

Since there is a documented workaround and there are known issues with disconnects in PDO, we will close this issue. Please feel free to reopen if needed.

**Closed by david-puglielli** 2020-02-21 21:56 UTC
Labels: by design
