### ISSUE TITLE
[Ubuntu 16.04] [PHP 7.0] Unable to connect: Adaptive Server is unavailable or does not exist (severity 9)

### ISSUE THREAD

**Issue by shakaran** [Microsoft/msphpsql#124] opened 2016-08-04 16:42 UTC
I am trying to connect with php 7.0 after install with:

```
sudo su
wget https://gallery.technet.microsoft.com/ODBC-Driver-13-for-Ubuntu-b87369f0/file/154097/2/installodbc.sh
sh installodbc.sh


$ sqlcmd -H xxx.xxx.xxx.xxx:xxxx -d MYTABLE -U MYUSER -P MYPASS
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x274D.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..


$ odbcinst -q -d -n "ODBC Driver 13 for SQL Server"
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
Threading=1
UsageCount=1

cat test.php 
<?php

$dbo = new PDO('dblib:host=xxx.xxx.xxx.xxx;dbname=MYTABLE;port=xxxx', 'MYUSER', 'MYPASS');
var_dump($dbo);

$ php7.0 test.php 
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] Unable to connect: Adaptive Server is unavailable or does not exist (severity 9) in test.php:3
Stack trace:
#0 test.php(3): PDO->__construct('dblib:host=xxx.xx...', 'MYUSER', 'MYPASS')
#1 {main}
  thrown in test.php on line 3
```

Connecting with tsql works fine:

```
$ LC_ALL=en_US.UTF-8 tsql -U MYUSER -H xxx.xxx.xxx.xxx -p xxxx -P MYPASS 

$ LC_ALL=en_US.UTF-8 tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v0.91
             freetds.conf directory: /etc/freetds
     MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 4.2
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes
```

I cannot even install php-pdodblib from PECL because it is not supported PHP 7.0

$ sudo pecl install PDO_DBLIB
pear/PDO_DBLIB requires PHP (version >= 5.0.3, version <= 6.0.0), installed version is 7.0.9-1+deb.sury.org~xenial+1
No valid packages found
install failed

I came here from [this stackoverflow post](http://stackoverflow.com/questions/34377338/linux-php-7-0-and-mssql-microsoft-sql). There are really support for PHP 7.0?

**Comment by xalopp** [comment] 2016-08-04 22:06
Did you try the option `-S` for `sqlcmd`?
```
sqlcmd -S 192.168.123.41 -d AdventureWorks2016CTP3 -U test -P test
```

The connection string in your example looks incorrect.  You're using `dblib` driver, but it would expect `sqlsrv` if you intend to use Linux driver provided by this project!
Please try this sample code:
```php
<?php

$serverName='192.168.123.41';
$database='AdventureWorks2016CTP3';
$uid='test';
$pwd='test';

$dbo = new PDO( "sqlsrv:server=$serverName ; Database = $database", $uid, $pwd);
var_dump($dbo);
```

**Comment by shakaran** [comment] 2016-08-05 05:16
@xalopp using -S param for sqlcmd give this error:

	Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
	Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x274D.
	Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.

Same using your example:

	sqlcmd -S 192.168.123.41 -d AdventureWorks2016CTP3 -U test -P test
	Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
	Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x274C.
	Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.

For the PDO test.php example if I change to sqlsrv it gives me:

    PHP Fatal error:  Uncaught PDOException: could not find driver

I have the .so in my machine:

I download and unzip from here (binaries GA):

    https://github.com/Azure/msphpsql/releases/download/v4.0.2-Linux/Ubuntu16.zip

According to my PHP 7.0 installation, my extension dir is:

	$ php7.0 -i | grep extension_dir
	extension_dir => /usr/lib/php/20151012 => /usr/lib/php/20151012

So I copy the files:

	$ sudo cp -rfv *.so /usr/lib/php/20151012/
	'php_pdo_sqlsrv_7_nts.so' -> '/usr/lib/php/20151012/php_pdo_sqlsrv_7_nts.so'
	'php_pdo_sqlsrv_7_ts.so' -> '/usr/lib/php/20151012/php_pdo_sqlsrv_7_ts.so'
	'php_sqlsrv_7_nts.so' -> '/usr/lib/php/20151012/php_sqlsrv_7_nts.so'
	'php_sqlsrv_7_ts.so' -> '/usr/lib/php/20151012/php_sqlsrv_7_ts.so'

And I create a .ini file for enable it:

    sudo touch /etc/php/7.0/mods-available/sqlsrv.ini

With the content:

	$ cat /etc/php/7.0/mods-available/sqlsrv.ini
	extension=php_pdo_sqlsrv_7_nts.so  
	extension=php_pdo_sqlsrv_7_ts.so  
	extension=php_sqlsrv_7_nts.so  
	extension=php_sqlsrv_7_ts.so

But I still didn't see the extension sqlsrv in modules list:

	$ php7.0 -m| grep sql
	mysqli
	mysqlnd
	pdo_mysql

So what I am doing wrong? Could you provide a .deb file for easy installation instead a zip?

**Comment by xalopp** [comment] 2016-08-05 11:28
Clean up your  INIs and use the NTS (non thread safe) version of the extension
`/etc/php/7.0/mods-available/sqlsrv.ini` contains
```
extension=php_sqlsrv_7_nts.so
```

`/etc/php/7.0/mods-available/pdo_sqlsrv.ini` contains
```
extension=php_pdo_sqlsrv_7_nts.so
```

Enable the PHP extensions
```
sudo phpenmod -s ALL  pdo_sqlsrv
sudo phpenmod -s ALL  sqlsrv
```

Make sure that PHP odbc extension is installed and enabled

```
sudo apt-get install php7.0-odbc
sudo phpenmod -s ALL pdo_odbc
sudo phpenmod -s ALL odbc
```

**Comment by shakaran** [comment] 2016-08-07 08:26
@xalopp Thanks for your great help!

I did your exact recommendations and I have some progress, but still not working perfectly:

	$ php7.0 -m | grep sql
	mysqli
	mysqlnd
	pdo_mysql
	pdo_sqlsrv
	sqlsrv

I change the DNS (Data Source Name) according to [the pdo sqlsrv documentation page](http://php.net/manual/en/ref.pdo-sqlsrv.connection.php) to

	'sqlsrv:server=XXX.XXX.XXX.XXX,XXXX;Database=XXXX;'
	
Note the port with semicolon too after the IP.

	$ cat test.php 
	<?php

	$dbo = new PDO('sqlsrv:server=XXX.XXX.XXX.XXX,XXXX;Database=XXXX;', 'XXXX', 'XXXX');
	var_dump($dbo);

After execute the test script I get:

	$ php7.0 test.php 
	PHP Fatal error:  Uncaught PDOException: SQLSTATE[08001]: [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x2746 in /home/shakaran/Documentos/ProjectsSSD/wyzen/go4wb_edit_module/edit_module/test.php:3
	Stack trace:
	#0 /test.php(3): PDO->__construct('sqlsrv:server=X...', 'XXXX', 'XXXXXX')
	#1 {main}
	  thrown in /test.php on line 3

So, how I solve the "TCP Provider: Error code 0x2746" error?

**Comment by xalopp** [comment] 2016-08-07 12:19
What is the output of `sqlcmd -S XXX.XXX.XXX.XXX,XXXX -U XXXX -P XXXX -d XXXX`?
Please fill in the proper data into the XXXXXX ;-)

I would expect an error message like `TCP Provider: An existing connection was forcibly closed by the remote host.` to be displayed.

In this case, please check firewall settings on client and server and anything between, connection settings on the database server, and anything else related to the network connection between client and server.

**Comment by xalopp** [comment] 2016-08-07 12:20
You might also consider tracing the client as explained in [Data Access Tracing with the ODBC Driver on Linux](https://msdn.microsoft.com/en-us/library/jj660948(v=sql.110).aspx)

**Comment by meet-bhagdev** [comment] 2016-08-07 23:50
@xalopp's recommendation is on point. We need to ensure sqlcmd/odbc connectivity works for the PHP Driver to work. 
@shakaran do you have any updates? Happy to assist with this issue.

**Comment by shakaran** [comment] 2016-08-08 07:30
Hi @meet-bhagdev @xalopp Sorry for delay, I am based in Spain and we have slightly timezone differences.

This is the error that I get:

$ sqlcmd -S XXX.XXX.XXX.XXX,XXXX -d XXXX -U XXXX -P XXXX
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Client unable to establish connection.

All firewalls between the client and server seems disabled as far I know.

This is the path for the inis:

	$ odbcinst -j 
	unixODBC 2.3.1
	DRIVERS............: /usr/local/etc/odbcinst.ini
	SYSTEM DATA SOURCES: /usr/local/etc/odbc.ini
	FILE DATA SOURCES..: /usr/local/etc/ODBCDataSources
	USER DATA SOURCES..: /home/shakaran/.odbc.ini
	SQLULEN Size.......: 8
	SQLLEN Size........: 8
	SQLSETPOSIROW Size.: 8

I put the .ini under ~/odbcinst.ini

I execute the command:

	$ strace -t -f -o trace_out.txt sqlcmd -S XXX.XXX.XXX.XXX,XXXX -d XXXX -U XXXX -P XXXX

And attaching the trace_out.txt file anonymized
[trace_out.txt](https://github.com/Azure/msphpsql/files/406274/trace_out.txt)

Let me know if you need more info ;) Thanks for all your support!

**Comment by shakaran** [comment] 2016-08-08 07:34
Sorry I just see that the right file should be /usr/local/etc/odbcinst.ini or /home/shakaran/.odbc.ini, so attaching new file where the function calls are properly traced.

File: 
[trace_out2.txt](https://github.com/Azure/msphpsql/files/406280/trace_out2.txt)

This is a snippet of the file:

	5763 09:31:40 access("/bid/enter FUNCTION: SNIWriteSync <API|SNI> 6#{SNI_Conn}, pConn: 00007F4484061B80{SNI_Conn*}, pPacket: 00007F4484061A10{SNI_Packet*}, pProvInfo: 0000000000000000{SNI_ProvInfo*}\n", F_OK) = -1 ENOEN$
	15763 09:31:40 access("/bid/enter FUNCTION: WriteSync <API|SNI> 7#, pPacket: 00007F4484061A10{SNI_Packet*}, pInfo: 0000000000000000{SNI_ProvInfo*}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/enter FUNCTION: PrepareForSyncCall <API|SNI> 7#, pPacket{SNI_Packet*}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: PrepareForSyncCall <RET|SNI> \n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/leave", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 sendto(4, "\22\1\0004\0\0\1\0\0\0\37\0\6\1\0%\0\1\2\0&\0\1\3\0'\0\4\4\0+\0"..., 52, MSG_NOSIGNAL, NULL, 0) = 52
	15763 09:31:40 access("/bid/FUNCTION: WriteSync <SNI> Send Packet, BytesWritten:52{DWORD}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: WriteSync <RET|SNI> 0{WINERR}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/leave", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: SNIWriteSync <RET|SNI> 0{WINERR}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/leave", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: SendPacket <TDS|IO> 00007F4484062B50{TDSOUTBUF}  9# 00007F4484061140{BATCHCTX}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/enter FUNCTION: SNIReadSync <API|SNI> 6#{SNI_Conn}, pConn: 00007F4484061B80{SNI_Conn*}, ppNewPacket: 00007F448C43B768{SNI_Packet**}, timeout: 7827\n", F_OK) = -1 ENOENT (No such file or direct$
	15763 09:31:40 access("/bid/enter FUNCTION: ReadSync <API|SNI> 7#, ppNewPacket: 00007F448C43B768{SNI_Packet**}, timeout: 7827\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/enter FUNCTION: WaitUntilSocketReadable <API|SNI> timeout: 7827{int}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 select(5, [4], NULL, NULL, {7, 827000}) = 1 (in [4], left {7, 666460})
	15763 09:31:40 access("/bid/FUNCTION: WaitUntilSocketReadable <RET|SNI> 0{WINERR}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/leave", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: SNIPacketAllocateEx2 <API|SNI> pConn: 00007F4484061B80{SNI_Conn*}, IOType: 0, consumer: 0\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: SNIPacketNew <API|SNI> pConn: 00007F4484061B80{SNI_Conn*}, IOType: 0\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 mprotect(0x7f4484064000, 4096, PROT_READ|PROT_WRITE) = 0
	15763 09:31:40 access("/bid/ObtainIDa 11#", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: SNI_Packet <ID|SNI> 00007F4484061AC0{.}", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: SNI_Packet <SNI> 11#{SNI_Packet} created by 6#{SNI_Conn}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: SNIPacketNew <RET|SNI> 00007F4484061AC0{SNI_Packet*}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: SNIPacketAllocateEx2 <RET|SNI> 00007F4484061AC0{SNI_Packet*}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/enter FUNCTION: PrepareForSyncCall <API|SNI> 7#, pPacket{SNI_Packet*}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: PrepareForSyncCall <RET|SNI> \n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/leave", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 recvfrom(4, "\4\1\0+\0\0\1\0\0\0\32\0\6\1\0 \0\1\2\0!\0\1\3\0\"\0\0\4\0\"\0"..., 4096, 0, NULL, NULL) = 43
	15763 09:31:40 access("/bid/FUNCTION: ReadSync <SNI> Receive Packet, BytesRead:43{DWORD}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: ReadSync <RET|SNI> 0{WINERR}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/leave", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: SNIReadSync <RET|SNI> 0{WINERR}, Packet: 00007F4484061AC0\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/leave", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: ReadPacket <TDS|IO> 00007F4484063B60{TDSINBUF} 9# 00007F4484061140{BATCHCTX}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: SNIPacketRelease <API|SNI> 11#{SNI_Packet}, pPacket: 00007F4484061AC0{SNI_Packet*}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: SNIPacketRelease <SNI> 11#{SNI_Packet} to pool\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/FUNCTION: Release <REFCOUNT> RefCount 2 9# 00007F4484061140{.}\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/enter FUNCTION: SNIAddProvider <API|SNI> 6#{SNI_Conn}, pConn: 00007F4484061B80{SNI_Conn*}, ProvNum: 6{ProviderNum}, pInfo: 00007F448C43B8C0\n", F_OK) = -1 ENOENT (No such file or directory)
	15763 09:31:40 access("/bid/enter FUNCTION: AddProvider <API|SNI> 6#{SNI_Conn}, pConn: 00007F4484061B80{SNI_Conn*}, ProvNum: 6{ProviderNum}, pInfo: 00007F448C43B750{LPVOID}\n", F_OK) = -1 ENOENT (No such file or director$

**Comment by xalopp** [comment] 2016-08-08 12:21
@shakaran what is the version of the MS SQL Server you're trying to connect to?
I've the feeling your issue is related to #100

**Comment by shakaran** [comment] 2016-08-08 12:34
I am using SQL Server 2008 on 32 bit.

Doing:

    $ sudo npm install -g sql-cli

And then trying to connect with:

	$ mssql -s XXX.XXX.XXX.XXX -o XXXX -d XXXXX -u XXXXX -p XXXXX
	Connecting to XXX.XXX.XXX.XXX...done

	sql-cli version 0.4.6
	Enter ".help" for usage hints.
	mssql> .tables
	database schema name type 
	---------- ------ --------------------------------- ----------
	XXXX dbo XXXX BASE TABLE
	XXXX dbo XXXX BASE TABLE

So, it is working perfectly for sql-cli but not for the PHP 7.0 driver on linux. So we can discard that it is a problem with firewall and the problem it is probably the driver. Also since I am using 2008 32 bit should be supported.

**Comment by xalopp** [comment] 2016-08-09 13:08
Unfortunately I'm not (yet) a MS SQL Server expert 😇 
Maybe @meet-bhagdev has an idea what's going wrong here.

**Comment by meet-bhagdev** [comment] 2016-08-10 17:29
@shakaran This is definitely weird. I will work with you to figure out what is going on here. Do you have an other versions of SQL Server(2012, 2014 etc) that we can try to test against? Also can you share what your odbc.ini file consists of? My hunch is there is a pre-configured dsn that is causing this problem.

**Comment by shakaran** [comment] 2016-08-10 18:44
@meet-bhagdev unfortunaly this is the "dev server" which is SQL Server 2008, with the "prod server" I have SQL Server 2005, and we cannot upgrade because we have a lot risky data (around 30 GB) and my client probably doesn't want spend time on the upgrade. If helps for more direct debugging, you can add me in skype with username "quijost", so we can have a direct chat a more quick turn around.

This are all the odbc.ini present in my system:

$ cat /usr/local/etc/odbcinst.ini
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
Threading=1
UsageCount=1
Trace=Yes

$ cat /home/shakaran/odbcinst.ini
Trace=Yes

$ cat /usr/local/etc/ODBCDataSources/*
cat: '/usr/local/etc/ODBCDataSources/*': No such file or directory

If you want provide me a 2012 or 2014 test server I can try to connect, but for my client this probably needs to work in 2008 at least.

**Comment by Inwerpsel** [comment] 2017-01-25 12:26
I am experiencing the same or a similar issue. Any updates on this yet?

**Comment by cherbert** [comment] 2017-02-09 13:22
I too have been tearing my hair out trying to get this working to connect to Microsoft SQL Server 2008 32bit. It simply doesn't work. This whole SQL Server and PHP 7.0 nonsense is beyond stupid. We are supposed to go forward not backward. I have moved to Python to get the job done and got connected within 5 minutes.

**Comment by v-dareck** [comment] 2017-02-09 18:57
Hi @Inwerpsel, @cherbert. What version of Windows are you running SQL Server on?

**Comment by cherbert** [comment] 2017-02-09 19:40
Windows Server 2003 32bit

**Comment by v-dareck** [comment] 2017-02-09 20:17
@cherbert  see the description of #252. Windows 2003 is no longer supported, [see here](https://www.microsoft.com/en-ca/cloud-platform/windows-server-2003). You should see about updating to a newer version of Windows.

**Comment by meet-bhagdev** [comment] 2017-02-11 00:28
@cherbert What version of the ODBC Driver are you using? It is likely that the issue is the TLS enforcement. Moreover what Python driver are you using to connect to SQL Server?

**Comment by cherbert** [comment] 2017-02-11 09:56
@meet-bhagdev I believe my PHP 7 install has ODBC 13 installed. Python is working out well for me now and I am using http://pymssql.org

**Comment by vanilla-thunder** [comment] 2017-03-21 14:52
suddenly got same problem with mssql11 (Server 2012) on Windows Server 2012 R2, though it worked before. No updates or patches were isntalled, no configuration was changed. Very strange

**Comment by vedmant** [comment] 2017-11-14 09:07
I started to have connection problem after upgrading my Linux packages. I use pdo_sqlsrv extension with installed Microsoft ODBC Driver for SQL Server. I tested it with sqlcmd tool which has the same issue connecting. 

When I try to connect with: `sqlcmd -S 192.168.0.190 -U sa -P Secret123` I get:

```
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Client unable to establish connection.
```

I dumped network traffic:
```
1389  socket(AF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
1389  connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
1389  socket(AF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
1389  connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
1390  socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_IP) = 3
1390  socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 3
1390  bind(3, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
1390  connect(3, {sa_family=AF_INET, sin_port=htons(1433), sin_addr=inet_addr("192.168.0.190")}, 16) = -1 EINPROGRESS (Operation now in progress)
1390  setsockopt(3, SOL_TCP, TCP_NODELAY, [1], 4) = 0
1390  setsockopt(3, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
1390  setsockopt(3, SOL_TCP, TCP_KEEPIDLE, [30], 4) = 0
1390  setsockopt(3, SOL_TCP, TCP_KEEPINTVL, [1], 4) = 0
1390  getpeername(3, {sa_family=AF_INET, sin_port=htons(1433), sin_addr=inet_addr("192.168.0.190")}, [16]) = 0
1390  getsockname(3, {sa_family=AF_INET, sin_port=htons(36313), sin_addr=inet_addr("192.168.0.252")}, [16]) = 0
1390  sendto(3, "\22\1\0004\0\0\1\0\0\0\37\0\6\1\0%\0\1\2\0&\0\1\3\0'\0\4\4\0+\0\1\5\0,\0\0\377\r\1\0\t\0\0\0\0\0\0\0\0\0", 52, MSG_NOSIGNAL, NULL, 0) = 52
1390  recvfrom(3, "\4\1\0+\0\0\1\0\0\0\32\0\6\1\0 \0\1\2\0!\0\1\3\0\"\0\0\4\0\"\0\1\377\t\0\10\234\0\0\0\0\0", 4096, 0, NULL, NULL) = 43
1390  sendto(3, "\22\1\1)\0\0\0\0\26\3\1\1\34\1\0\1\30\3\3}\v}\216\0\360_\300/\360\377mKe\254\215\235#X5Fo#\270MOA\227\t*1\v\0\0\254\3000\300,\300(\300$\300\24\300\n\0\245\0\243\0\241\0\237\0k\0j\0i\0h\0009\0008\0007\0006\0\210\0\207\0\206\0\205\3002\300.\300*\300&\300\17\300\5\0\235\0=\0005\0\204\300/\300+\300'\300#\300\23\300\t\0\244\0\242\0\240\0\236\0g\0@\0?\0>\0003\0002\0001\0000\0\232\0\231\0\230\0\227\0E\0D\0C\0B\3001\300-\300)\300%\300\16\300\4\0\234\0<\0/\0\226\0A\300\22\300\10\0\26\0\23\0\20\0\r\300\r\300\3\0\n\0\7\300\21\300\7\300\f\300\2\0\5\0\4\0\377\1\0\0C\0\v\0\4\3\0\1\2\0\n\0\n\0\10\0\27\0\31\0\30\0\26\0#\0\0\0\r\0 \0\36\6\1\6\2\6\3\5\1\5\2\5\3\4\1\4\2\4\3\3\1\3\2\3\3\2\1\2\2\2\3\0\17\0\1\1", 297, MSG_NOSIGNAL, NULL, 0) = 297
1390  recvfrom(3, "", 4096, 0, NULL, NULL) = 0
1390  shutdown(3, SHUT_WR)              = 0
1390  +++ exited with 0 +++
1389  +++ exited with 1 +++
```

OS: CentOS Linux release 7.4.1708 (Core)
SQL SERVER: Windows Server 2003 R2 SP2 SQL Server 9.0.2204

I'd really appreciate any help here!

**Comment by David-Engel** [comment] 2017-11-15 23:10
Hi @vedmant 

You should open a new issue with your problem. Commenting on closed issues won't get your problem noticed very quickly.

**Comment by david-puglielli** [comment] 2019-02-27 22:44
Closing due to inactivity. Please reopen if necessary.

**Closed by david-puglielli** 2019-02-27 22:44 UTC
