### ISSUE TITLE
Installation on macOS not working

### ISSUE THREAD

**Issue by fredmatrack** [Microsoft/msphpsql#413] opened 2017-05-31 08:28 UTC
Hi

I'm trying to install and use the driver on mac OS Sierra 10.12.5. This system is also running macOS Server.

I installed PHP Version 7.1.4 via Liip on our server which is now running as the default PHP version for our webserver: https://atlas.piustien.net/phpinfo.php

I installed unixODBC 2.3.4 and when using sqlcmd from the terminal, I can connect to a MSSQL Server using Microsoft ODBC Driver 13.

I also installed

```
sudo pecl install sqlsrv-4.2.0preview
sudo pecl install pdo_sqlsrv-4.2.0preview
```
after running
`xcode-select --install`
otherwise I got errors about sql.h

When I run a script:
`<?php 

	error_reporting(E_ALL);
	ini_set('display_errors', 1);
	
	$mssql_host_uniflow  = '192.168.64.123';
	$mssql_user_uniflow  = 'sa';
	$mssql_pass_uniflow  = 'PASSWORD';
	$mssql_data_uniflow  = 'DataBase';
	
	
	$dbh = new PDO ("sqlsrv:Server=$mssql_host_uniflow;Database=$mssql_data_uniflow","$mssql_user_uniflow","$mssql_pass_uniflow");`

I get this error:

`Fatal error: Uncaught PDOException: SQLSTATE[IMSSP]: This extension requires the Microsoft ODBC Driver 13 for SQL Server to communicate with SQL Server. Access the following URL to download the ODBC Driver 13 for SQL Server for x64: http://go.microsoft.com/fwlink/?LinkId=163712 in /Library/Server/Web/Data/Sites/Default/test.php on line 12`

What's going wrong? How can I make sure PHP can find the ODBC Driver 13?

**Comment by meet-bhagdev** [comment] 2017-05-31 20:33
@fredmatrack are you able to connect using sqlcmd?

**Comment by fredmatrack** [comment] 2017-05-31 20:45
Yes, that's no problem.

**Comment by ulvii** [comment] 2017-05-31 21:25
Hi @fredmatrack ,
Please post the output of the following commands:
```
1. odbcinst -j
2. odbcinst -q -d -n "ODBC Driver 13 for SQL Server"
3. sudo find /usr 2>/dev/null -name "libodbc*"
```

**Comment by fredmatrack** [comment] 2017-06-01 14:08
This is what I get when running these commands:

```
atlas:~ admin$ odbcinst -j
unixODBC 2.3.4
DRIVERS............: /usr/local/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/etc/odbc.ini
FILE DATA SOURCES..: /usr/local/etc/ODBCDataSources
USER DATA SOURCES..: /Users/admin/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

```
atlas:~ admin$ odbcinst -q -d -n "ODBC Driver 13 for SQL Server"
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/usr/local/lib/libmsodbcsql.13.dylib
??=
```

```
atlas:~ admin$ sudo find /usr 2>/dev/null -name "libodbc*"
Password:
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbc.2.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbc.a
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbc.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbccr.2.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbccr.a
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbccr.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbcinst.2.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbcinst.a
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbcinst.dylib
/usr/local/lib/libodbc.2.dylib
/usr/local/lib/libodbc.a
/usr/local/lib/libodbc.dylib
/usr/local/lib/libodbc.la
/usr/local/lib/libodbccr.2.dylib
/usr/local/lib/libodbccr.a
/usr/local/lib/libodbccr.dylib
/usr/local/lib/libodbccr.la
/usr/local/lib/libodbcinst.2.dylib
/usr/local/lib/libodbcinst.a
/usr/local/lib/libodbcinst.dylib
/usr/local/lib/libodbcinst.la
/usr/local/Library/Formula/libodbc++.rb
/usr/local/php5-7.1.4-20170506-100436/lib/libodbc.a
/usr/local/unixODBC/lib/libodbc.2.dylib
/usr/local/unixODBC/lib/libodbc.dylib
/usr/local/unixODBC/lib/libodbc.la
/usr/local/unixODBC/lib/libodbccr.2.dylib
/usr/local/unixODBC/lib/libodbccr.dylib
/usr/local/unixODBC/lib/libodbccr.la
/usr/local/unixODBC/lib/libodbcinst.2.dylib
/usr/local/unixODBC/lib/libodbcinst.dylib
/usr/local/unixODBC/lib/libodbcinst.la
```

```
atlas:~ admin$ php -i | grep "Configure Command"
Configure Command =>  './configure'  '--prefix=/usr/local/php5' '--with-apxs2=/usr/sbin/apxs' '--with-config-file-scan-dir=/usr/local/php5/php.d' '--with-libxml-dir=shared,/usr' '--with-openssl=/usr/local/php5' '--with-zlib=/usr' '--with-zlib-dir=/usr' '--with-gd' '--with-ldap' '--with-xmlrpc' '--enable-exif' '--enable-soap' '--enable-wddx' '--enable-ftp' '--with-iodbc' '--enable-sockets' '--with-bz2=/usr' '--enable-zip' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-mbstring' '--enable-bcmath' '--enable-calendar' '--with-mhash' '--enable-fpm' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--enable-pcntl' '--enable-dtrace' '--disable-phpdbg' '--enable-opcache' '--with-icu-dir=/usr/local/php5' '--with-xsl=shared,/usr/local/php5' '--with-imap=shared,../imap-2007f' '--with-kerberos=/usr' '--with-imap-ssl=/usr/local/php5' '--with-gettext=/usr/local/php5' '--with-curl=shared,/usr/local/php5' '--with-png-dir=/usr/local/php5' '--with-jpeg-dir=/usr/local/php5' '--enable-gd-native-ttf' '--with-freetype-dir=/usr/local/php5' '--with-pgsql=shared,/usr/local/php5' '--with-pdo-pgsql=shared,/usr/local/php5' '--with-mcrypt=shared,/usr/local/php5' '--with-tidy=/usr/local/php5' '--with-gmp=shared,/usr/local/php5' '--with-readline=shared,/usr/local/php5' '--with-libxml-dir=/usr/local/php5' 'CFLAGS=-Os -mmacosx-version-min=10.10 -I/usr/local/php5/include -arch x86_64 -no-cpp-precomp -DENTROPY_CH_ARCHS='
```

I hope you can see what's wrong...

**Comment by ulvii** [comment] 2017-06-02 01:23
Hi @fredmatrack ,

You are running into issues, because php that you are using is compiled with idbc option ( `--with-idobc` ). Both SQLSRV, PDO_SQLSRV and the underlying MSODBCSQL have no idobc support, but instead they depend on unixODBC as a Driver Manager. Looks like you have both idobc and unixODBC installed. There reason why you can connect using `sqlcmd `is because MSODBCSQL has unixODBC as a dependency. 

To be able to use the drivers, php should be compiled with unixODBC ( `--with-unixODBC` ). You can either use Homebrew package ( `brew install php71` ) or compile php manually. 

Let me know if you have any other questions.

**Comment by fredmatrack** [comment] 2017-06-02 08:37
Thank you very much for your help. It works now!

**Comment by ulvii** [comment] 2017-06-02 17:07
Great, I am closing the issue. Feel free to re-open it if you still need help.

**Closed by ulvii** 2017-06-02 17:07 UTC
Labels: Configuration

**Comment by radzzii** [comment] 2019-04-16 09:48
@ulvii help me please. ive been strugling for this issue, for too long, and now im so frustated, because i still can't fix this :'(. thanks Sir

the problem is, i cant access the sqlsrv with php (via browser), but its ok via terminal.
the error is: 

`Error information:
SQLSTATE: 01000
Code: 0
Message: [unixODBC][Driver Manager]Can't open lib '/usr/local/lib/libmsodbcsql.17.dylib' : file not found`

`odbcinst -j
unixODBC 2.3.7
DRIVERS............: /usr/local/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/etc/odbc.ini
FILE DATA SOURCES..: /usr/local/etc/ODBCDataSources
USER DATA SOURCES..: /Users/radzinugrahapurba/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
`

`odbcinst -q -d -n "ODBC Driver 17 for SQL Server"
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/usr/local/lib/libmsodbcsql.17.dylib
UsageCount=1
`
`sudo find /usr 2>/dev/null -name "libodbc*"
Password:
/usr/local/php5-7.2.9-20180821-074958/lib/libodbc.a
/usr/local/lib/libodbcinst.2.dylib
/usr/local/lib/libodbccr.dylib
/usr/local/lib/libodbcinst.a
/usr/local/lib/libodbcinst.dylib
/usr/local/lib/libodbc.a
/usr/local/lib/libodbc.2.dylib
/usr/local/lib/libodbccr.2.dylib
/usr/local/lib/libodbccr.a
/usr/local/lib/libodbc.dylib
/usr/local/Cellar/unixodbc/2.3.7/lib/libodbcinst.2.dylib
/usr/local/Cellar/unixodbc/2.3.7/lib/libodbccr.dylib
/usr/local/Cellar/unixodbc/2.3.7/lib/libodbcinst.a
/usr/local/Cellar/unixodbc/2.3.7/lib/libodbcinst.dylib
/usr/local/Cellar/unixodbc/2.3.7/lib/libodbc.a
/usr/local/Cellar/unixodbc/2.3.7/lib/libodbc.2.dylib
/usr/local/Cellar/unixodbc/2.3.7/lib/libodbccr.2.dylib
/usr/local/Cellar/unixodbc/2.3.7/lib/libodbccr.a
/usr/local/Cellar/unixodbc/2.3.7/lib/libodbc.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbcinst.2.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbccr.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbcinst.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbc.2.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbccr.2.dylib
/usr/local/Cellar/unixodbc/2.3.4/lib/libodbc.dylib
`
`php -i | grep "Configure Command"
Configure Command =>  './configure'  '--prefix=/Applications/XAMPP/xamppfiles' '--with-apxs2=/Applications/XAMPP/xamppfiles/bin/apxs' '--with-config-file-path=/Applications/XAMPP/xamppfiles/etc' '--with-mysql=mysqlnd' '--enable-inline-optimization' '--disable-debug' '--enable-bcmath' '--enable-calendar' '--enable-ctype' '--enable-ftp' '--enable-gd-native-ttf' '--enable-magic-quotes' '--enable-shmop' '--disable-sigchild' '--enable-sysvsem' '--enable-sysvshm' '--enable-wddx' '--with-gdbm=/Applications/XAMPP/xamppfiles' '--with-jpeg-dir=/Applications/XAMPP/xamppfiles' '--with-png-dir=/Applications/XAMPP/xamppfiles' '--with-freetype-dir=/Applications/XAMPP/xamppfiles' '--with-zlib=yes' '--with-zlib-dir=/Applications/XAMPP/xamppfiles' '--with-openssl=/Applications/XAMPP/xamppfiles' '--with-xsl=/Applications/XAMPP/xamppfiles' '--with-ldap=/Applications/XAMPP/xamppfiles' '--with-gd' '--with-imap=/bitnami/xamppunixinstaller72stack-osx-x64/src/imap-2007e' '--with-imap-ssl' '--with-gettext=/Applications/XAMPP/xamppfiles' '--with-mssql=shared,/Applications/XAMPP/xamppfiles' '--with-pdo-dblib=shared,/Applications/XAMPP/xamppfiles' '--with-sybase-ct=/Applications/XAMPP/xamppfiles' '--with-mysql-sock=/Applications/XAMPP/xamppfiles/var/mysql/mysql.sock' '--with-mcrypt=/Applications/XAMPP/xamppfiles' '--with-mhash=/Applications/XAMPP/xamppfiles' '--enable-sockets' '--enable-mbstring=all' '--with-curl=/Applications/XAMPP/xamppfiles' '--enable-mbregex' '--enable-zend-multibyte' '--enable-exif' '--with-bz2=/Applications/XAMPP/xamppfiles' '--with-sqlite=shared,/Applications/XAMPP/xamppfiles' '--with-sqlite3=/Applications/XAMPP/xamppfiles' '--with-libxml-dir=/Applications/XAMPP/xamppfiles' '--enable-soap' '--with-xmlrpc' '--enable-pcntl' '--with-mysqli=mysqlnd' '--with-pgsql=shared,/Applications/XAMPP/xamppfiles/' '--with-iconv=/usr' '--with-pdo-mysql=mysqlnd' '--with-pdo-pgsql=/Applications/XAMPP/xamppfiles/postgresql' '--with-pdo_sqlite=/Applications/XAMPP/xamppfiles' '--with-icu-dir=/Applications/XAMPP/xamppfiles' '--enable-fileinfo' '--enable-phar' '--enable-zip' 'ac_cv_decimal_fp_supported=no' '--without-libzip' '--disable-huge-code-pages' 'CFLAGS=-std=gnu99 -Qunused-arguments -I/Applications/XAMPP/xamppfiles/include/c-client -Qunused-arguments -I/Applications/XAMPP/xamppfiles/include/libpng -I/Applications/XAMPP/xamppfiles/include/freetype2 -O3 -L/Applications/XAMPP/xamppfiles/lib -I/Applications/XAMPP/xamppfiles/include -I/Applications/XAMPP/xamppfiles/include/ncurses -arch x86_64'`

`otool -L /usr/local/lib/libmsodbcsql.17.dylib
/usr/local/lib/libmsodbcsql.17.dylib:
	/usr/local/opt/msodbcsql17/lib/libmsodbcsql.dylib (compatibility version 0.0.1, current version 3.1.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1259.11.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/lib/libodbcinst.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)

the : /usr/local/opt/msodbcsql17/lib/libmsodbcsql.dylib not found`

thank you Sir, hope you can help me.

**Comment by yitam** [comment] 2019-04-16 15:15
@radzzii `/usr/local/lib/libmsodbcsql.17.dylib` is not found, as you said. However, we can't help you without more info. For example, please provide the version of your macOS, how did you install ODBC 17, how did you install PHP, which versions of sqlsrv drivers, etc. Please create a new issue and answer the questions.
