### ISSUE TITLE
No x64 NTS PHP 7.0 PDO builds?

### ISSUE THREAD

**Issue by echodreamz** [Microsoft/msphpsql#469] opened 2017-07-07 17:02 UTC
The PECL page lists 7.1 NTS x64 builds for the PDO extension, but does not have any for 7.0. 4.3.0RC1 was available in this configuration.

**Comment by Hadis-Fard** [comment] 2017-07-07 18:32
@echodreamz thanks for reporting this issue, we are investigating the PECL builds, meanwhile you can get the binaries from [4.3.0 release ](https://github.com/Microsoft/msphpsql/releases/tag/v4.3.0)

**Comment by Hadis-Fard** [comment] 2017-07-07 21:17
@echodreamz the issue is fixed now, and dlls are up in the [PDO_SQLSRV pecl page](https://pecl.php.net/package/pdo_sqlsrv/4.3.0/windows ). thanks for reporting it 👍

**Closed by Hadis-Fard** 2017-07-07 21:17 UTC
