### ISSUE TITLE
Reuse of prepared statements is.. impossible

### ISSUE THREAD

**Issue by david-garcia-garcia** [Microsoft/msphpsql#60] opened 2015-07-04 01:24 UTC
The whole point of the PDO thing is to be able to reuse statements.

Investigating why PDO preparation was not working, even when reusing statements, I found out that:

1) When MSSQL PDO prepares a statement with a string parameter, it uses the exact length of the string for the data type during the preparation: nvarchar(1), nvarchar(2), nvarchar(...), nvarchar(n) 

So I have a query with a string bound to one of it's parameters, say ":p0". If the string length of ":p0" changes between runs the statement will never be reused. But... if the string stays the same length, the  prepared statement will be reused.

2) At the same time I found out that even when passing integers to BindParam if you do not explictly tell the driver it's an INT it will bind it as a string (1 -> nvarchar(1), 12 -> nvarchar(2) ) and this, I guess, has potential performance penalties on the SQL Server side.

BindParam states that if no type is specified the default is PDO::PARAM_STRING. But even if you do not explictly bind the parameters with BindParam (for example with $statement->query($args) where $args are the parameters) it will still bind everything as a string.

So.... (2) is not that of a big issue (depending of the performance implications of sending a string against an integer column). 

But (1) is really defeating the whole purpose of prepared queries. And considering that the default behaviour of the driver is to use prepared statements (DIRECT_QUERIES need to be explictly turned on) I guess this can be considered a bug.

I've been kind enough to prepare a sample script. Open SQL Server profiler and see how none of the 5 the tests cases - except the last one - is reusing prepared statements.

The behaviour in (1) makes it nearly imposible to reuse prepared statements.

``` php

$conn = $databases['default']['default'];
$host = $conn['host']; 
$database = $conn['database']; 
$username =  $conn['username'];
$password = $conn['password'];

$cnn = new \PDO("sqlsrv:server=$host;Database=$database",  $username, $password);

$stmt = $cnn->prepare('SELECT COUNT(*) FROM VARIABLE WHERE NAME = :p1');

// Because the length of :p1 changes between statements
// the driver is preparing it again and again for every execution...
for ($x = 1; $x < 5; $x ++) {
  $p1 = str_pad('_', $x);
  $stmt->bindParam(':p1', $p1);
  $stmt->execute();
  $res = $stmt->fetchColumn();
}

// Let's reuse the object reference and see if there
// is any improvement, but nothing yet, statement is prepared every single time.
$stmt->bindParam(':p1', $p1);
for ($x = 1; $x < 5; $x ++) {
  $p1 = str_pad('_', $x);
  $stmt->execute();
  $res = $stmt->fetchColumn();
}

// Is BindValue any better? Nope.
for ($x = 1; $x < 5; $x ++) {
  $p1 = str_pad('_', $x);
  $stmt->bindValue(':p1', $p1);
  $stmt->execute();
  $res = $stmt->fetchColumn();
}

// I guess this mess will not happen with integers...
// No luck. MSSQL PDO does not even acknowledge these are integers probably
// making queries underperform due to casts on the SQL Server side.
for ($x = 1; $x < 5; $x ++) {
  $y = (int) str_pad('1', $x, '0');
  $stmt->bindValue(':p1', $y);
  $stmt->execute();
  $res = $stmt->fetchColumn();
}
// Let's help it a little bit with PDO::PARAM_INT
// At least this one did reuse the statement....
for ($x = 1; $x < 5; $x ++) {
  $y = (int) str_pad('1', $x, '0');
  $stmt->bindValue(':p1', $y, PDO::PARAM_INT);
  $stmt->execute();
  $res = $stmt->fetchColumn();
}

```

**Comment by meet-bhagdev** [comment] 2015-08-31 07:27
@david-garcia-garcia 
Do you still need help with this?

**Comment by david-garcia-garcia** [comment] 2015-08-31 13:34
It would be nice to be able to use prepared statements on a driver that supports such a feature.

As it currently is, prepared statements are close to impossible to use on any real life scenario where you expect string length of parameters to vary between runs of the same statement.

Prepared statement reuse yields very nice performance gains on some workloads - specially on cloud deployments such as Azure - because it reduces verbosity between application and database server.

**Comment by Joe-U-Questionmark** [comment] 2015-11-05 14:43
@meet-bhagdev Is there a plan to fix this? It seems like a big win for performance...

**Comment by KyleWiering** [comment] 2016-12-09 19:19
I think I have figured out how to make them all nvarchar(max) instead of the specific size...

     $statement->bindParam($param, $value, \PDO::PARAM_STR, 30 );

What I cannot figure out is how to get a varchar instead of a nvarchar...

**Comment by Joe-U-Questionmark** [comment] 2017-01-18 11:51
@KyleWiering looks like we are getting somewhere!
@meet-bhagdev looks like a bit of internal digging could solve this?

**Comment by v-dareck** [comment] 2017-01-19 01:54
Hi @david-garcia-garcia what are the events that you are seeing in SQL Profiler that show the statement is not being re-used?

With your sample script I see an initial 'Prepare SQL' event, followed by multiple 'Exec Prepared SQL' and finally an 'Unprepare SQL' at the end.

**Comment by meet-bhagdev** [comment] 2017-02-16 00:47
@david-garcia-garcia we are looking into this right now. Have you had a chance to look at @v-dareck's questions above?

**Comment by Hadis-Fard** [comment] 2017-08-23 22:21
@david-garcia-garcia Closing this issue since we're not able to reproduce this issue, and can re-use prepared stmt. Feel free to re-open it if you need further assistance :)

**Comment by paq85** [comment] 2017-09-19 09:21
Hi, look like I've faced a serious bug when reusing prepared statements.

When I reuse prepared statement for a query with `OUTPUT inserted.*` and do `->fetch();` I get the result of the very first result I've got with this `OUTPUT`.

Example:
```php
/* @var \PDOStatement $st */
$query = 'UPDATE products SET price = :price OUTPUT inserted.* WHERE id = :id';
$st = new \PDOStatement($query); // assume that this is a statement I'm about to reuse

$st->bindValue(':id', 10, \PDO::PARAM_INT);
$st->bindValue(':price', 9900, \PDO::PARAM_INT);
$st->execute(); // I can see in the DB that proper row has been updated as requested
$data = $st->fetch();
// $data contains ['id' => 10, 'price' => 9900] // OK

$st->bindValue(':id', 33, \PDO::PARAM_INT);
$st->bindValue(':price', 1599, \PDO::PARAM_INT);
$st->execute(); // I can see in the DB that proper row has been updated as requested
$data = $st->fetch();
// $data contains ['id' => 10, 'price' => 9900] // WHAT?! BUG in driver?
// I should get ['id' => 33, 'price' => 1599] as that's now in the DB for row with id = 33
```

Could you have a look @meet-bhagdev @Hadis-Fard ?

**Comment by nemchik** [comment] 2017-12-28 14:59
So this issue still seems to be open. Since the last comment seems to indicate that this is not actually an issue, can anyone confirm if prepared statements are actually usable?

**Comment by v-kaywon** [comment] 2018-01-03 01:17
@nemchik , from my debugging using david-garcia-garcia's sample script, prepared statements are reusable. Closing this issue.

**Closed by v-kaywon** 2018-01-03 01:17 UTC
Labels: PDO_SQLSRV
