### ISSUE TITLE
'UTF-8' is not a supported encoding for the CharacterSet connection option

### ISSUE THREAD

**Issue by munfor** [Microsoft/msphpsql#106] opened 2016-07-06 10:17 UTC
I'm using the driver SQLSRV32 to connect SQL Server 2008.
My web server is running an Apache/2.4.12 (Win32)  PHP/5.6.8

The connection was working fine with this configuration:

```
$connectionInfo = [
   "Database" => "Database", 
   "UID" => "user",
   "PWD" => "my_pass",
   "CharacterSet" => "UTF-8"];

sqlsrv_connect($server, $connectionInfo);
```

But suddenly the connection is established successfully, other times a connection error occurs:

```
       'UTF-8' is not a supported encoding for the CharacterSet connection option.
```

Is as the driver can not determine the CharacterSet defined in the array connection. But sometimes it works, sometime not.

Someone had the same problem?

**Comment by meet-bhagdev** [comment] 2016-07-06 18:42
Is this an intermittent issue? Did you run into this previously? I also recommend you check out the following link for more information around Character-Set with the PHP Driver: https://blogs.msdn.microsoft.com/brian_swan/2011/02/24/sql-server-driver-for-php-connection-options-characterset/

**Comment by munfor** [comment] 2016-07-08 15:28
Thanks for the information.

I found that the driver throw an error at ['conn.cpp](https://github.com/Azure/msphpsql/blob/7cb7c799164e4e699fea6d09ba4de869b9689204/sqlsrv/conn.cpp#L70)' at line 70 or 78:

`THROW_SS_ERROR( conn, SS_SQLSRV_ERROR_CONNECT_ILLEGAL_ENCODING, encoding );`

But CharacterSet value 'UTF-8' is a good parameter. The proof is that it work fine most of time, but sometimes the error SS_SQLSRV_ERROR_CONNECT_ILLEGAL_ENCODING is shown.

I don't know if it is a driver bug or a database error. May be the database responds to the driver it doesn't support the UTF-8 encoding? I don't know.

Thanks for help

**Comment by ericpetroelje** [comment] 2016-09-12 19:50
I too have run into this same issue - exactly as munfor describes (most of the time I'm able to connect successfully, but occasionally this error is thrown on connect)

**Comment by meet-bhagdev** [comment] 2016-11-10 01:10
@munfor @ericpetroelje We are not able to repro this issue in our labs. Is there a script/some other form of repro we can use?

**Comment by meet-bhagdev** [comment] 2016-11-23 00:03
@ericpetroelje Closing the issue for now as we are not able to reproduce this in our labs. Feel free to reopen with a repro/script if you are still running into this issue.

**Closed by meet-bhagdev** 2016-11-23 00:03 UTC

**Comment by michallohnisky** [comment] 2017-04-06 11:56
I got similar problem, but my error message was `'UTF8' is not a supported encoding for the CharacterSet connection option.` (missing hyphen). I had to explicitly set the `charset` to `UTF-8`. But when I remove the charset option, I don't get the error message anymore and everything works. It's strange.

Keep this issue closed for now.

**Comment by reksc** [comment] 2018-10-04 09:21
This above occurs when configuring the latest version of Doctrine ORM within Symfony to use sqlsrv. Might be more of a Doctrine issue.
