### ISSUE TITLE
After package upgrade from repository php fails to connect SQL server (Ubuntu 16.04)

### ISSUE THREAD

**Issue by kviktorman** [Microsoft/msphpsql#684] opened 2018-02-11 18:24 UTC
+## Driver version or file name

 +## SQL Server version
MSSQL 2014 running on Windows

 +## Client operating system
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

 +## PHP version
PHP 7.0 was originally installed, with that I have had the same issue after odbc driver package upgrade. I thought maybe upgrading php would solve the issue, but not.

Now:
PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  6 2018 16:11:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2-3+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

 +## Microsoft ODBC Driver version
 +Please tell us which version of the Microsoft ODBC Driver you are using.
/opt/microsoft/msodbcsql/etc/odbcinst.ini

[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-17.0.so.1.1

 +## Table schema
 +Please tell us the table schema
 Not important.

 +## Problem description
After package upgrade from repository I'm not able to connect to the database server from php.
repo: https://packages.microsoft.com/ubuntu/16.04/prod

Before update the database connection was working fine. After upgrade with sqlcmd I'm still able to connect., but php fails to connect.

From the error I guess there is some extra configuration which I miss. To make php use the right odbc driver (17). Can you please let me know what i miss? 
Thanks

 +Please share more details with us.
This is my error message:
Array ( [0] => Array ( [0] => IMSSP [SQLSTATE] => IMSSP [1] => -49 [code] => -49 [2] => This extension requires the Microsoft ODBC Driver 11 or 13 for SQL Server. Access the following URL to download the ODBC Driver 11 or 13 for SQL Server for x64: http://go.microsoft.com/fwlink/?LinkId=163712 [message] => This extension requires the Microsoft ODBC Driver 11 or 13 for SQL Server. Access the following URL to download the ODBC Driver 11 or 13 for SQL Server for x64: http://go.microsoft.com/fwlink/?LinkId=163712 ) [1] => Array ( [0] => IM002 [SQLSTATE] => IM002 [1] => 0 [code] => 0 [2] => [unixODBC][Driver Manager]Data source name not found, and no default driver specified [message] => [unixODBC][Driver Manager]Data source name not found, and no default driver specified ) )

 +## Expected behavior and actual behavior
The database connection would established.

 +## Repro code
 +Please share repro code with us, or tell us how to reproduce the issue.

**Comment by lukeify** [comment] 2018-02-12 10:20
Similar situation here, Ubuntu 16.04. I confirmed my version was 17.x with: `dpkg -l msodbcsql`. Downgraded via `ACCEPT_EULA=Y apt-get install msodbc=13.1.9.2-1` for now fixes the problem temporarily; but this needs a fix.

**Comment by timnash** [comment] 2018-02-12 21:43
Same issue here, Ubuntu 16.04. Downgraded back to 13.1. I'm running PHP 7.1 FPM w/ nginx.

**Comment by alpharokot** [comment] 2018-02-13 03:52
Downgrade instruction:

`root@pc:~# apt-get remove msodbcsql
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  msodbcsql mssql-tools
0 upgraded, 0 newly installed, 2 to remove and 3 not upgraded.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
(Reading database ... 223240 files and directories currently installed.)
Removing mssql-tools (17.0.1.1-1) ...
Removing msodbcsql (17.0.1.1-1) ...

root@pc:~# apt-cache madison msodbcsql
 msodbcsql | 17.0.1.1-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
 msodbcsql | 13.1.9.2-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
 msodbcsql | 13.1.9.1-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
 msodbcsql | 13.1.9.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
 msodbcsql | 13.1.8.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
 msodbcsql | 13.1.7.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
 msodbcsql | 13.1.6.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
 msodbcsql | 13.1.4.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
 msodbcsql | 13.1.3.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
 msodbcsql | 13.1.1.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
 msodbcsql | 13.1.0.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
 msodbcsql | 13.0.1.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages

root@pc:~# apt-get install msodbcsql=13.1.9.2-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  msodbcsql
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 3 643 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 msodbcsql amd64 13.1.9.2-1 [3 643 kB]
Fetched 3 643 kB in 4s (814 kB/s)        
Preconfiguring packages ...
Selecting previously unselected package msodbcsql.
(Reading database ... 223211 files and directories currently installed.)
Preparing to unpack .../msodbcsql_13.1.9.2-1_amd64.deb ...
Unpacking msodbcsql (13.1.9.2-1) ...
Setting up msodbcsql (13.1.9.2-1) ...

root@pc:~# apt-cache madison mssql-tools
mssql-tools | 17.0.1.1-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
mssql-tools | 14.0.6.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
mssql-tools | 14.0.5.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
mssql-tools | 14.0.4.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
mssql-tools | 14.0.3.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
mssql-tools | 14.0.2.0-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages
mssql-tools | 14.0.1.246-1 | https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages

root@pc:~# ACCEPT_EULA=Y apt-get install mssql-tools=14.0.6.0-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  mssql-tools
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 1 264 kB of archives.
After this operation, 0 B of additional disk space will be used.
0% [Working]
Get:1 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 mssql-tools amd64 14.0.6.0-1 [1 264 kB]
Fetched 1 264 kB in 7s (167 kB/s)                                                                                                                                                                                   
Preconfiguring packages ...
Selecting previously unselected package mssql-tools.
(Reading database ... 223227 files and directories currently installed.)
Preparing to unpack .../mssql-tools_14.0.6.0-1_amd64.deb ...
Unpacking mssql-tools (14.0.6.0-1) ...
Setting up mssql-tools (14.0.6.0-1) ...

root@pc:~# service apache2 restart

root@pc:~# apt-mark hold mssql-tools
mssql-tools set on hold.

root@pc:~# apt-mark hold msodbcsql
msodbcsql set on hold.
`

**Comment by david-puglielli** [comment] 2018-02-13 19:24
@kviktorman @lukeify @timnash @alpharokot You need to use version 5.1.0 of the drivers or above to use ODBC driver 17. You can install the most recent preview using `pecl install sqlsrv-5.2.0RC1` or `pecl install pdo_sqlsrv-5.2.0RC1`, or they are available on the [releases page](https://github.com/Microsoft/msphpsql/releases).

**Comment by Azaret** [comment] 2018-02-14 12:46
Are you saying that MS push in stable a driver that need another package version which is still in RC?
Is this serious?

**Comment by rapemer** [comment] 2018-02-14 13:01
same issue, I had to downgrade with instructions by @alpharokot

**Comment by david-puglielli** [comment] 2018-02-14 18:59
@Azaret No, the last stable release of the driver was 4.3.0. Since then, we have pushed several preview releases for the next version of the driver. New features added since 4.3.0 require a newer version of the ODBC driver, which up until recently was also in preview. ODBC driver 17 is now stable, but the PHP driver is not. At no point did we put out a stable driver PHP driver release that depends on a non-stable ODBC driver.

**Comment by lukeify** [comment] 2018-02-15 02:27
> At no point did we put out a stable driver PHP driver release that depends on a non-stable ODBC driver.

Yes, but isn't inverse true? `msodbcsql` was released as the default installation target, and yet requires a release candidate PHP driver, which _does not_ install by default.

**Comment by jeffbeagley** [comment] 2018-02-15 02:29
You can explicitly install v13.x of the msodbcsql then tell it not to
update in order to use 4.3.0

**Comment by kviktorman** [comment] 2018-02-15 12:45
Fair enough, thank you for the explanation. Now we know whats the situation.

For application developers (like myself) this process is a bit strange, but I can understand it and I'm not going to complain about it. It will take just time without achievements.

Since this place is more about contribution lets keep it that way.

Lets assume what we have now:
- We have stable odbc version in the repository which is going to upgraded if we don't put it on hold.
- We can use the latest stable odbc if we upgrade the php sqlsrv drivers to RC.
- We have a ReadMe where this note is hardly to find. 

0. Confirmation

- I upgraded the sqlsrv php drivers to RC and they are working for me.
- OS: Ubuntu 16.04.3 LTS
- PHP : 7.2.2-3+ubuntu16.04.1+deb.sury.org+1 from ondrej/php repositry as it is in the install guide
(Since I already upgraded to 7.2 and I don't want to downgrade just for the testing purpose we need a confirmation that its working with 7.0 and / or 7.1 like this as well )

#>sudo pecl uninstall sqlsrv
#>sudo pecl uninstall pdo_sqlsrv
#>sudo pecl install sqlsrv-5.2.0RC1
#>sudo pecl install pdo_sqlsrv-5.2.0RC1

1. Update Readme:
- Here on github the "Step 3: Install the Microsoft PHP Drivers for SQL Server" should contain this small note about.
- Also on this installation page this small note should appear:
https://www.microsoft.com/en-us/sql-server/developer-get-started/php/ubuntu/step/2.html
- Maybe we should also add a small note into the driver installation as well. Like if you want to use it with php you have to put the package on hold or you have to use it with RC driver.

I can update the readme with this note here on github. Just let me know to which repo should I push the PR. But for the MS page update I don't have the rights....

**Comment by yitam** [comment] 2018-04-05 22:16
hi @kviktorman, you might have noticed ODBC packages have undergone some changes. For suggestions or questions regarding ODBC packages, please visit the [blog announcement of ODBC 17.1](https://blogs.msdn.microsoft.com/sqlnativeclient/2018/04/03/odbc-driver-17-1-for-sql-server-released/).

Please let us know if you still have questions concerning PHP. Otherwise, we will close this issue. Thanks!

**Closed** 2018-04-06 06:12 UTC

**Comment by kviktorman** [comment] 2018-04-06 06:16
Hi @yitam, thank you for the link. I have closed it.
