### ISSUE TITLE
Is_callable throws an exception if PDOStatement method does not exist.

### ISSUE THREAD

**Issue by Beakerboy** [microsoft/msphpsql#1258] opened 2021-05-12 15:12 UTC
## PHP Driver version or file name
 + latest using `pecl install sqlsrv pdo_sqlsrv` on 2021-05-12
 ## SQL Server version
 + 2019
 ## Client operating system
 + Linux
 ## PHP version
+ 8.0.2
 ## Microsoft ODBC Driver version
+ msodbcsql17
 ## Table schema
+ None
 ## Problem description
+ calling `is_callable()` on the sqlsrv version of a PDOStatement throws an exception if the method does not exist. `PDOException: SQLSTATE[IMSSP]: This function is not implemented by this driver.`
 ## Expected behavior and actual behavior
+ it should return false
 ## Repro code or steps to reproduce
 ```php
$pdo = new \PDO("sqlsrv:Server=localhost;Database=mydrupalsite", "sa", "Password12!");
$pdoStatement = $pdo->prepare("SELECT id FROM test");

// This Works
$functionExists = is_callable([$pdoStatement, 'bindParam']);
$this->assertTrue($functionExists);

// This throws an exception: 
$functionExists = is_callable([$pdoStatement, 'boo']);
$this->assertFalse($functionExists); 
```

**Comment by yitam** [comment] 2021-05-12 18:00
Thank you @Beakerboy for bringing this to our attention. While I understand it may not be an expected behavior to throw an exception, it's been like this since version 3.0 for pdo_sqlsrv. We will get back to you on this.

**Comment by Beakerboy** [comment] 2021-05-12 18:37
The following was recently added to Drupal core:
```php
public function __call($method, $arguments) {
    if (is_callable([$this->getClientStatement(), $method])) {
      @trigger_error("StatementWrapper::{$method} should not be called in drupal:9.1.0 and will error in drupal:10.0.0. Access the client-level statement object via ::getClientStatement(). See https://www.drupal.org/node/3177488", E_USER_DEPRECATED);
      return call_user_func_array([$this->getClientStatement(), $method], $arguments);
    }
    throw new \BadMethodCallException($method);
  }
  ```

It successfully runs on Postgres, MySQL, and SQLite...potentially others as well. The GOOD thing is that in this particular case, an exception would be thrown regardless, but of a different type.

**Comment by yitam** [comment] 2021-05-12 18:42
Thanks @Beakerboy so it's a matter of throwing different exception? 
I mean we can easily change pdo_sqlsrv to return `false` instead of throwing an exception, but there might be users out there who have relied on the exceptions

**Comment by yitam** [comment] 2021-05-18 17:57
Hi @Beakerboy 
I've fixed this and you should see the change in the next preview release.

**Comment by yitam** [comment] 2021-09-08 18:50
Closing this issue as per [5.10.0-beta1](
https://github.com/microsoft/msphpsql/releases/tag/v5.10.0-beta1)

**Closed by yitam** 2021-09-08 18:50 UTC
Labels: PDO_SQLSRV, Linux
