### ISSUE TITLE
MySQL enums fetched through OPENQUERY have trailing spaces

### ISSUE THREAD

**Issue by ktsharp** [microsoft/msphpsql#931] opened 2019-02-14 00:30 UTC
## PHP Driver version or file name
ExtensionVer => 5.2.0
## SQL Server version
Microsoft SQL Server 2014 (SP1-GDR) (KB4019091) - 12.0.4237.0 (X64) 
## Client operating system
CentOS Linux release 7.2.1511 (Core)
## PHP version
PHP 7.0.30
## Microsoft ODBC Driver version
ODBC Driver 13 for SQL Server
## Problem description
When running a query on SQL Server that fetches columns through a linked MySQL server, MySQL fields of ENUM type have additional whitespace at the end if they are not the longest string in the enum.

I am attempting to migrate an application from using pdo_dblib to pdo_sqlsrv and this was discovered because when using pdo_dblib there is no additional spaces.  I have found workarounds (including casting the enum field to CHAR within the OPENQUERY) but no way to make it properly return values without trailing spaces
## Expected behavior and actual behavior
Expected: Enum fields returned the same as they are in the database.
Actual: Some enum fields have trailing spaces 
## Repro code or steps to reproduce
MySQL:
```
CREATE TABLE `enum_test` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(8,2) NOT NULL,
  `test_type` ENUM('dollar','percent','reallylongname') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB
;

INSERT INTO `enum_test` (`amount`, `test_type`)
VALUES (10.00, 'dollar'), (5.00, 'percent'), (2.40, 'reallylongname')
;
```
 
PHP:
```
    $sql = "
        SELECT id, amount, test_type
          FROM OPENQUERY(MySQL_Dev, 
                   'SELECT id, amount, test_type FROM kevins.enum_test'  
                )";

    $res = $pdo->fetchAll($sql);

    var_dump($res);`
```

Result:
```
array(3) {
  [0] =>
  array(3) {
    'id' =>
    string(1) "1"
    'amount' =>
    string(5) "10.00"
    'test_type' =>
    string(14) "dollar        "
  }
  [1] =>
  array(3) {
    'id' =>
    string(1) "2"
    'amount' =>
    string(4) "5.00"
    'test_type' =>
    string(14) "percent       "
  }
  [2] =>
  array(3) {
    'id' =>
    string(1) "3"
    'amount' =>
    string(4) "2.40"
    'test_type' =>
    string(14) "reallylongname"
  }
}
```

**Comment by david-puglielli** [comment] 2019-02-14 20:50
@ktsharp We do not support MySQL, so we can't really help you. As SQL Server doesn't have an enum type, I'm not sure it can be reasonably expected to handle MySQL enums properly, so if you have a functioning workaround, that's good. 

I would suggest trying the query with `sqlcmd` and seeing if you get the same issue. If so then it is not related to the PHP driver in any case. If however you get the correct result, then there may be a bug in the PHP driver's handling of strings, which would require further investigation.

**Comment by ktsharp** [comment] 2019-02-15 20:34
@david-puglielli Indeed, when I run the query through SQL Server Management Studio or through sqlcmd it does not have the extra spaces at the end of it.  This was also not an issue with the old pdo_dblib driver which is we are moving away from because it is not well supported in PHP 7.0+.

The workaround I found that if I change the part inside of the OPENQUERY from:
`SELECT id, amount, test_type FROM kevins.enum_test`
to
`SELECT id, amount, CAST(test_type AS CHAR) AS test_type FROM kevins.enum_test`
then the result in PHP doesn't have any additional whitespace.  This makes me think that the driver is handling it like the spaces at the end are significant characters and casting it to CHAR makes it understand what the result is.

**Comment by david-puglielli** [comment] 2019-02-15 22:09
Interesting. Can you upgrade to the latest version of the PHP driver? Some changes have been made to string handling since version 5.2.0 that may address this issue. Though you would need to upgrade PHP to 7.1 or higher as well.

**Comment by ktsharp** [comment] 2019-02-18 23:06
@david-puglielli I tried it on a virtualbox running PHP7.2 and ODBC Driver version 17 and got the same result

**Comment by david-puglielli** [comment] 2019-02-19 18:59
Can you try with the latest SQLSRV/PDO_SQLSRV driver? Use `pecl install sqlsrv-5.5.0preview` or `pecl install pdo_sqlsrv-5.5.0preview` to install.

**Comment by ktsharp** [comment] 2019-02-19 21:00
```
kevins@kevins-VirtualBox:~$ pecl list
Installed packages, channel pecl.php.net:
=========================================
Package    Version      State
pdo_sqlsrv 5.5.0preview devel
sqlsrv     5.5.0preview devel
```
Ran the query using both sqlsrv and pdo_sqlsrv.  Same results as before.

**Comment by david-puglielli** [comment] 2019-02-19 21:46
Thank you @ktsharp we will investigate and get back to you.

**Comment by david-puglielli** [comment] 2019-02-28 00:01
@ktsharp Is it possible for you to provide a repro script that does not depend on MySQL? Any script (and any database/table schema) that might show this issue will help.

**Comment by david-puglielli** [comment] 2019-03-13 21:39
@ktsharp After investigating, sqlcmd actually produces the same trailing spaces. It's not obvious because sqlcmd produces formatted output, but by inspecting packets we found that it is SQL Server and not the PHP driver (or the ODBC driver) that converts the enum to a char fixed width type, and char types will produce trailing spaces. This behaviour is correct on the part of the PHP and ODBC drivers.

I agree that it's not obvious that this is not a bug, but the bug likely resides in SQL Server (or the OLE DB driver layer). If you want to report this as a bug or suggest an improvement, try [here](https://feedback.azure.com/forums/908035-sql-server), or you can discuss it further [here](https://social.msdn.microsoft.com/Forums/en-US/home).

**Comment by david-puglielli** [comment] 2019-03-19 23:50
Closing this issue. Please feel free to reopen if necessary.

**Closed by david-puglielli** 2019-03-19 23:50 UTC
Labels: area: query-execution
