### ISSUE TITLE
Error [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]SSL Provider: [error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers]

### ISSUE THREAD

**Issue by rachid-c** [microsoft/msphpsql#962] opened 2019-03-25 13:59 UTC
.+Please check the [FAQ (frequently-asked questions)](https://github.com/Microsoft/msphpsql/wiki/FAQ) first. If you have other questions or something to report, please address the following:

 +## PHP Driver version or file name
 + 5.6.1
 +## SQL Server version
 + SQL Server 2016
 +## Client operating system
 + SUSE Linux Enterprise Server 15
 +## PHP version
 + 7.2.5
 +## Microsoft ODBC Driver version
 + ODBC Driver 17 
 +## Table schema
 + Not Relevant
 +## Problem description
 +$connectioninfo=array("UID" => $DB_user, "PWD" => $DB_pass, "Encrypt" => false, "Datab\
ase"=>$DB_dbName);
        $conn=sqlsrv_connect( $DB_host, $connectioninfo);
                      if  ( $conn  === FALSE)
                      {
                           echo "There has been an error connecting to the back-end sy\
stems supporting the Online directory.";
                            die( print_r( sqlsrv_errors(), true));
                        }

The connection to the database on the command line works fine using sqsh from FreeTDS.

 +## Expected behavior and actual behavior
 +
 +## Repro code or steps to reproduce

**Comment by rachid-c** [comment] 2019-03-25 14:02
Forgot to say we are using openssl 1.1 instead of openssl-1.0.2 see issue #680

**Comment by david-puglielli** [comment] 2019-03-25 19:05
@rachid-c This is a known bug which is fixed in an upcoming release, so please stay tuned!

**Comment by rachid-c** [comment] 2019-03-26 10:12
Many thanks David

**Comment by david-puglielli** [comment] 2019-08-07 01:46
@rachid-c The latest release of the ODBC driver (version 17.4) should fix this problem. Please upgrade your msodbcsql17 installation using your package manager and let us know if the problem is fixed.

**Comment by david-puglielli** [comment] 2019-08-12 21:44
Closing issue due to inactivity. Please reopen if necessary.

**Closed by david-puglielli** 2019-08-12 21:44 UTC
