### ISSUE TITLE
Problem with PHP7 and round function when I enable any MsSQL module

### ISSUE THREAD

**Issue by i2dcarrasco** [microsoft/msphpsql#840] opened 2018-09-04 16:47 UTC
+## PHP Driver version or file name
sqlsrv-5.3.0 and pdo_sqlsrv-5.3.0 

 +## SQL Server version
Don't really care, because is a PHP function changed without connect to any server.

 +## Client operating system
Debian 8 Jessie

 +## PHP version
7.0.31

 +## Microsoft ODBC Driver version
msodbcsql                            13.1.9.2-1
msodbcsql17                        17.2.0.1-1
mssql-tools                           17.2.0.1-1

 +## Table schema
 No BBDD is used

 +## Problem description
 When I enable any of the two modules on PHP (sqlsrv.so or pdo_sqlsrv.so), php round function changes the decimal separator from point to comma. 

 +## Expected behavior and actual behavior
Is expected to keep the php round function intact, because changing this function breaks pages.

With module enable:
```
# php -r 'echo round(85.20, 1);'
85,2
```

When is disabled (normal behaviour):
```
# php -r 'echo round(85.20, 1);'
85.2
```

 +## Repro code or steps to reproduce

1. Just install the module following the instructions of the MS webpage (pecl install...)
2. Install MsSQL ODBC driver msodbcsql17 following the MS instructions too
3. Enable the module on php fpm or cli conf.d folder
4. Enjoy how it breaks you're webpage changing the php round function

Thanks!!

**Comment by i2dcarrasco** [comment] 2018-09-04 19:29
Hello, thanks for your response.

The server locales are:
```
LANG=es_ES.UTF-8
LANGUAGE=
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"
LC_ALL=
```
Greetings.

**Comment by yitam** [comment] 2018-09-04 21:04
Hi @i2dcarrasco 

Please check if the default encoding for Apache is configured and if so, is it [set to UTF-8](https://stackoverflow.com/questions/913869/how-to-change-the-default-encoding-to-utf-8-for-apache)?

**Comment by yitam** [comment] 2018-09-04 21:11
In a command prompt, I could reproduce this issue when my encoding was set to es_ES ISO-8859-1.

This might be a [useful reference](https://www.w3.org/International/questions/qa-htaccess-charset) to you

**Comment by i2dcarrasco** [comment] 2018-09-05 08:53
Hello,

I still investigating the problem, but after some changes looks like maybe is a problem of es_ES locales on Debian 8.
I've a machine with Debian 9 and locale es_ES.UTF-8 that works perfect. The machine that fails have Debian 8 and same locale, but when I change the locale to en_US.UTF-8 it starts to works so looks like es_ES.UTF-8 + PHP7.0 on Debian 8 make it fail.

Now I'll try to upgrade the SO to see if upgradeing to Debian 9 will fix it.

Greetings and thanks for all your help.

**Comment by yitam** [comment] 2018-09-05 14:59
Sounds good! Thanks @i2dcarrasco and let us know how it goes.

**Comment by yitam** [comment] 2018-09-19 16:41
Any update, @i2dcarrasco? If we don't hear from you for the next few days, we will close this issue.

**Comment by i2dcarrasco** [comment] 2018-09-20 10:56
Hi,

For now the only I know is that using spanish locales (es_ES.utf-8), the module changes the point to comma, and using english locales (en_US.UTF-8), it keeps the point.
For now I was not able to test the solution on the final server, but looks like will be fixed.

The only thing that I don't understand is why the SQL module changes the behaviour of an external function. It's true that decimal separator is comma in spanish, but before enable the module and even in spanish locales the separator of that function is point.

I'll give a try to change just the LC_MONETARY.

Greetings!

**Comment by i2dcarrasco** [comment] 2018-09-20 11:15
Hello again,

Finally looks like just changing LC_NUMERIC works:
```
# cat /etc/default/locale 
LANG=es_ES.UTF-8
LC_NUMERIC="en_US.UTF-8"
```
```
# php /server/nfs/projects/alantra_web/www/test.php
85.2
```

Greetings!!

**Comment by yitam** [comment] 2018-09-20 15:55
Sounds great, @i2dcarrasco! I'm closing this issue, but please feel free to reopen anytime.

**Comment by decece** [comment] 2019-07-30 07:50
The locales issue is still happening.

We were having problems with the numbers' encoding and we spent a lot of time trying to debug the issue. The culprit was the PDO_SQLSRV driver that was installed (via PECL) to connect to a remote MS SQL machine. It somehow overrides the LC_Numeric set by environment and php.ini (in our case, es_ES).

The local MySQL database contained numbers created with the es_ES locale, and when values were read, they were displayed incorrectly, similarly to what happened to @i2dcarrasco .

Pdo_sqlsrv 5.6.1 stable on Debian 9. Issue both happening on PHP 7.1 and 7.2 (at the moment the extension is activated).

**Comment by david-puglielli** [comment] 2019-07-31 20:37
@decece It sounds like there may be an issue with sqlsrv's locale handling when the locale is set in php.ini. We will investigate and get back to you.

**Comment by yitam** [comment] 2019-08-08 22:33
hi @decece to help us investigate please provide 

1. a repro script, preferably PHP script
1. table schema, if applicable
1. locale settings in your environment 
1. how you set locale in php.ini 

For the last point above, did you set [intl.default_locale](https://www.php.net/manual/en/intl.configuration.php#ini.intl.default-locale)?

The clearer the instructions / steps the better, such that we may be able to reproduce the issue.

**Comment by yitam** [comment] 2019-08-09 21:23
Hi @decece 

Upon further investigation, I figure your problem is in fact the opposite of the original problem reported by @i2dcarrasco

In his case, he wanted the decimal dot rather than using the comma (defined by the env locale settings). In your case, you want to preserve the comma as the decimal point. I've done some quick test in PHP, as shown in the following script:

```
<?php

echo setlocale(LC_NUMERIC, NULL) . PHP_EOL; // expect es_ES.UTF-8
$number = 10/3;
echo $number . PHP_EOL;                     // expect something like 3,3333333333333

try {
    $conn = new PDO("sqlsrv:server=$server ; Database = $database", $uid, $pwd);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    // Comment this line below to fetch numeric data as strings
    $conn->setAttribute(PDO::SQLSRV_ATTR_FETCHES_NUMERIC_TYPE, true);

    $tsql = 'DROP TABLE myTable; CREATE TABLE myTable (col1 float, col2 real)';
    $stmt = $conn->query($tsql);

    $tsql = "INSERT INTO myTable (col1, col2) VALUES (:c1, :c2)";
    $stmt = $conn->prepare($tsql);
    $stmt->bindValue(':c1', $number);
    $stmt->bindValue(':c2', $number);
    $stmt->execute();

    $tsql = 'SELECT * FROM myTable';
    $stmt = $conn->query($tsql);

    $result = $stmt->fetchAll();
    var_dump($result);

} catch (PDOException $e) {
    var_dump($e->errorInfo);
}

unset($conn);
?>
```

The results show commas in the numbers:

```
es_ES.UTF-8
3,3333333333333
array(1) {
  [0]=>
  array(4) {
    ["col1"]=>
    float(3,3333333333333)
    [0]=>
    float(3,3333333333333)
    ["col2"]=>
    float(3,3333332538605)
    [1]=>
    float(3,3333332538605)
  }
}
```

However, this is _not_ the case when the numeric data are fetched as strings. To do this, set `PDO::SQLSRV_ATTR_FETCHES_NUMERIC_TYPE` to `false` or simply comment the line in the php script above (because it is by default `false`). 

When they are fetched as strings, you see decimal points, not commas. 

Please verify, at your earliest convenience.

**Comment by decece** [comment] 2019-08-13 10:55
Hello @yitam,
I'll provide some information about our settings:
- Server running Debian 9 Stretch. 
Locales used: es_ES.UTF-8 and en_US.UTF-8. It was later changed to just es_ES (when we were debugging this error).
- PHP 7.1 and 7.2, with intl.default_locale set to es_ES (set manually in php.ini).
- The MySQL (local) schema had a number stored as:  _decimal(12,4)_. On PHPMyAdmin any number stored in that column shows as, for instance, 7.5.

We were running Magento on that machine, and the problem appeared the moment we activated PDO_SQLSRV extension. We tried both in PHP 7.1 and 7.2, and the problem arose only when activating the extension. A 7.5 number would appear on the site as 7.500.000,00.

We had to connect to a remote MS SQL machine to keep the prices updated, that's why we started using the PDO extension. As we had to keep going with the project (we had to meet some deadlines) we decided to drop PDO_SQLSRV entirely and use Microsoft's ODBC Driver v17, in which the issue didn't arise.

**Comment by yitam** [comment] 2019-08-13 15:42
Thanks @decece for the update. I have a few more questions:

About your locale settings, is it mainly en_US.UTF-8 except for LC_NUMERIC you use es_ES.UTF-8? I've done some brief testing setting `intl.default_locale` to `es_ES` but did not find anything unusual. If you think intl functions were affected, please provide the steps to reproduce.

Also, it isn't clear to me if you meant that by enabling the pdo_sqlsrv extension, your pdo_mysql script(s) is(are) affected. Or did you mean that pdo_sqlsrv does not correctly show numeric data when fetching from MySQL tables? 

Again, it helps us investigate if you can provide a pdo script.

**Comment by yitam** [comment] 2019-09-06 15:34
Hi @decece 

We could not seem to reproduce the issues that you have encountered, and due to insufficient details and inactivity, we will close this issue.

**Closed by yitam** 2019-09-06 15:34 UTC
Labels: Configuration
