### ISSUE TITLE
Inserting empty resultset into a temp table in procedure confuses the result set handling 

### ISSUE THREAD

**Issue by slaakso** [Microsoft/msphpsql#858] opened 2018-10-02 07:53 UTC
## PHP Driver version 

Linux sqlsrv 5.3.0 / 5.4.0

## SQL Server version

Any

## Client operating system

Ubuntu 16.04
Can be reproduced with the Docker image at https://hub.docker.com/r/lbosqmsft/mssql-php-msphpsql/

## PHP version

PHP 7.0.15-0ubuntu0.16.04.2

Microsoft ODBC Driver version

msodbcsql/xenial,now 13.1.4.0-1

## Stored procedure in the server

```
create procedure sp_test
as
begin

-- Remove the comments from following two lines to make this procedure to work with sqlsrv
-- create table #dummy ( sqlsrvbug int )
-- insert into #dummy values (1)

create table #test ( a int )

/* Insert an empty resultset */
insert into #test
select 1
from (
  select 1 as v
) as q 
where q.v  = 99

select 2

end
go
```

## Problem description
 
If a stored procedure starts with an empty insert into a temp table, the sqlsrv-driver gets confused and is uable to return data from any of the queries that follow.

## Expected behavior and actual behavior

The PHP code executes the stored procedure and loops through the result sets. It should show the output second query, but instead stops at the first temp table insert.

Expected result:
```
Result set #1
array(0) {
}
Result set #2
array(1) {
  [0]=>
  array(1) {
    [0]=>
    int(2)
  }
}
```

Actual behavior:
```
Result set #1
array(0) {
}
```

## Repro code or steps to reproduce

1. Get the docker image from https://hub.docker.com/r/lbosqmsft/mssql-php-msphpsql/
2. Add the procedure above to SQL Server
3. Fill in the credentials and run the PHP script from command line:

`# php empty_rs.php "sp_test"`

empty_rs.php:
```
<?php 

$tSQL = $argv[1];

$serverName = "SERVER";
$connectionOptions = array(
  "Database" => "DATABASE",
  "Uid" => "USERNAME",
  "PWD" => "PASSWORD"
);
$conn = sqlsrv_connect($serverName, $connectionOptions);

$resultset = array();

$i = 1; 
$stmt = sqlsrv_query($conn, $tSQL);
do {
  echo 'Result set #'.$i++.PHP_EOL;
  $resultset = array();
  while ($row = sqlsrv_fetch_array($stmt, SQLSRV_FETCH_NUMERIC)) {
    array_push($resultset, $row);
  }
  var_dump($resultset);
} while (sqlsrv_next_result($stmt));

```

Note that if one adds an insert into a dummy temp table to the beginning of the procedure, everything works.

**Comment by david-puglielli** [comment] 2018-10-02 23:21
@slaakso Thank you for reporting this. Do you know if docker is necessary to reproduce this bug? We have not been able to outside of docker.

**Comment by slaakso** [comment] 2018-10-04 15:12
Docker is not necessary. 

Did the installation on Ubuntu 16.04.2 LTS and tested it with that with same results. The database used is Microsoft SQL Server 2012 - 11.0.5343.0 (Intel X86).

Does look like the bug is not related to PHP extension, but mabye to unixodbc, as the same behavior can be replicated with sqlcmd. The sp_test below is the same as the sp_test above.

```
$ sqlcmd -S 172.16.125.128 -U user -P pass
1> sp_test
2> go

(0 rows affected)
1> select 'whatever'
2> go
SqlState 24000, Invalid cursor state
1> select 'whatever again'
2> go
SqlState 24000, Invalid cursor state
1> 
```

So the sqlcmd's connection is messed up and no more commands can be processed. If the dummy temporary table + insert is added to beginning of procedure, everything is working ok. Same as with the PHP script.

**Comment by david-puglielli** [comment] 2018-10-04 17:50
I think you are correct, it sounds like this is a unixODBC issue. The default unixODBC that comes with Ubuntu 16.04 is version 2.3.1, and many bugs have been fixed since then. I suggest upgrading your unixODBC to the [latest](http://www.unixodbc.org) (you will probably need to install it from source).

**Comment by slaakso** [comment] 2018-10-06 19:10
Yes, this was a unixODBC issue. Fixed with newer unixODBC. Tested with unixODBC 2.3.7.

**Comment by david-puglielli** [comment] 2018-10-06 22:51
Thanks, we will close this issue now. Feel free to reopen if the problem crops up again.

**Closed by david-puglielli** 2018-10-06 22:51 UTC
